-- ----------------------
-- sauvegarde de la base Manga au 25-May-2017
-- ----------------------


-- -----------------------------
-- creation de la table achat
-- -----------------------------
CREATE TABLE `achat` (
  `id` tinyint(10) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) NOT NULL,
  `tome` varchar(255) NOT NULL,
  `date_sortie` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

-- -----------------------------
-- creation de la table anime
-- -----------------------------
CREATE TABLE `anime` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(200) DEFAULT NULL,
  `episode` varchar(200) DEFAULT NULL,
  `date` varchar(200) DEFAULT NULL,
  `theme` varchar(500) DEFAULT NULL,
  `saison` varchar(250) DEFAULT NULL,
  `duree` varchar(200) DEFAULT NULL,
  `format` varchar(255) DEFAULT NULL,
  `oav` varchar(255) DEFAULT NULL,
  `film` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `date_modif` datetime(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=205 DEFAULT CHARSET=utf8;

-- -----------------------------
-- creation de la table manga
-- -----------------------------
CREATE TABLE `manga` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `tome` varchar(25) CHARACTER SET latin1 DEFAULT NULL,
  `chapitre` varchar(25) CHARACTER SET latin1 DEFAULT NULL,
  `datecreation` varchar(25) CHARACTER SET latin1 DEFAULT NULL,
  `genre` varchar(25) CHARACTER SET latin1 DEFAULT NULL,
  `statut` varchar(25) CHARACTER SET latin1 DEFAULT NULL,
  `theme` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `Resume` varchar(5000) CHARACTER SET latin1 DEFAULT NULL,
  `format` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=110 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;



-- -----------------------------
-- insertions dans la table achat
-- -----------------------------
INSERT INTO achat VALUES('9', 'Spice and Wolf', '14', 'Juillet 2017');
INSERT INTO achat VALUES('10', 'Highschool dxd', '10', '28 juin 2017');

-- -----------------------------
-- insertions dans la table anime
-- -----------------------------
INSERT INTO anime VALUES('1', 'Black Lagoon', '27', '2002', 'Aventure Gangster', '3', '30', 'PC', 'non', 'non', 'black.jpg', '');
INSERT INTO anime VALUES('2', 'HIgh School of the Dead', '12', '2010', 'Ecchi, Horreur', '1', '30', 'PC', 'non', 'non', 'highschool.jpg', '');
INSERT INTO anime VALUES('3', 'Kanokon', '12', '2008', 'Surnaturel, Romance', '1', '25', 'PC', 'non', 'non', 'kanokon.jpg', '');
INSERT INTO anime VALUES('4', 'XxxHolic', '41', '2006', 'Magie', '4', '25', 'PC', 'non', 'non', 'xxxholic.png', '');
INSERT INTO anime VALUES('5', 'Dragon Ball Z', '289', '1989', 'Action Arts Martiaux', '1', '25', 'Internet', 'non', 'non', 'dragon ball z.png', '');
INSERT INTO anime VALUES('6', 'Naruto', '135', '2002', 'Action, Ninja', '1', '25', 'PC', 'non', 'non', 'naruto.png', '');
INSERT INTO anime VALUES('7', 'One Piece', '680', '1997', 'Action, Pirate', '17', '25', 'PC', 'non', 'non', 'one piece.jpg', '');
INSERT INTO anime VALUES('8', 'Full Metal Panic', '36', '2002', 'Action Mecha', '2', '25', 'PC', 'non', 'non', 'panic.jpg', '');
INSERT INTO anime VALUES('9', 'Gundam Wing', '49', '1995', 'Action Mecha', '1', '25', 'DVD', 'non', 'non', 'wing.jpg', '');
INSERT INTO anime VALUES('10', 'Gundam 00', '50', '2007', 'Action Mecha', '2', '25', 'PC', 'non', 'non', 'wing.jpg', '');
INSERT INTO anime VALUES('11', 'Evangelion', '26', '1995', 'Robot Psychologique', '1', '25', 'DVD', 'non', 'non', 'evangelion.jpg', '');
INSERT INTO anime VALUES('12', 'Inu x Boku SS', '13', '2012', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Inu x Boku SS.jpg', '');
INSERT INTO anime VALUES('13', '11 Eyes', '12', '2009', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', '11eyes.jpg', '');
INSERT INTO anime VALUES('14', 'Akane-Iro ni Somaru Saka', '13', '2008', 'Romance Vie Scolaire', '1', '25', 'Internet', 'non', 'non', 'Akaneiro ni Somaru Saka.jpg', '');
INSERT INTO anime VALUES('15', 'Angel beats', '13', '2010', 'Romance, Action', '1', '25', 'Internet', 'non', 'non', 'Angel beats.jpg', '');
INSERT INTO anime VALUES('16', 'Angel s Tail', '12', '2001', 'Romance Surnaturel', '1', '25', 'Internet', 'non', 'non', 'Angel s Tail.jpg', '');
INSERT INTO anime VALUES('17', 'Bakuman', '75', '2010', 'Romance Manga', '3', '25', 'Internet', 'non', 'non', 'bakuman.jpg', '');
INSERT INTO anime VALUES('18', 'Hiiro no Kakera', '26', '2012', 'Harem Inverse Romance', '2', '25', 'Internet', 'non', 'non', 'hiiro no kakero.jpg', '');
INSERT INTO anime VALUES('19', 'C3', '12', '2011', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'c3.jpg', '');
INSERT INTO anime VALUES('20', 'Rail Wars', '12', '2014', 'Train Romance', '1', '25', 'Internet', 'non', 'non', 'rail wars.jpg', '');
INSERT INTO anime VALUES('21', 'Le Pacte des Yokai', '52', '2005', 'Surnaturel', '4', '25', 'Internet', 'non', 'non', 'le pacte.jpg', '');
INSERT INTO anime VALUES('22', 'Saint Seiya', '114', '1986', 'Action Mythologie', '3', '25', 'PC', 'non', 'non', 'saint seiya.jpg', '');
INSERT INTO anime VALUES('23', 'Dc Da Capo', '24', '2008', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'dcdacapo.jpg', '');
INSERT INTO anime VALUES('24', 'Full Metal Alchemist', '51', '2000', 'Science Fantaisie Action', '1', '25', 'PC', 'non', 'non', 'FullmetalAlchemist.png', '');
INSERT INTO anime VALUES('25', 'Shinkyoku soukai polyphonica', '24', '2007', 'Musique Romance Surnaturel', '2', '25', 'PC', 'non', 'non', 'shinkyoku_soukai_polyphonica.jpg', '');
INSERT INTO anime VALUES('26', 'Kiss x Sis', '12', '2008', 'Romance Ecchi', '1', '25', 'PC', 'non', 'non', 'kiss-x-sis.jpg', '');
INSERT INTO anime VALUES('27', 'Date A Live', '13', '2012', 'Harem Romance', '1', '25', 'Internet', 'non', 'non', 'Date A Live.jpg', '');
INSERT INTO anime VALUES('28', 'dearS', '13', '2012', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'dearS.jpg', '');
INSERT INTO anime VALUES('29', 'Dragon Crisis', '12', '2011', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Dragon Crisis.jpg', '');
INSERT INTO anime VALUES('30', 'Gosick', '24', '2010', 'Policier', '1', '25', 'Internet', 'non', 'non', 'Gosick.jpg', '');
INSERT INTO anime VALUES('31', 'Guilty Crown', '22', '2011', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Guilty Crown.jpg', '');
INSERT INTO anime VALUES('32', 'Heroic Age', '26', '2007', 'Romance Action', '1', '25', 'Internet', 'non', 'non', 'Heroic Age.jpg', '');
INSERT INTO anime VALUES('33', 'Hoshizora e Kakaru Hashi', '13', '2011', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Hoshizora e Kakaru Hashi.jpg', '');
INSERT INTO anime VALUES('34', 'Kaze Stigma', '24', '2007', 'Romance Aventure', '1', '25', 'Internet', 'non', 'non', 'Kaze Stigma.jpg', '');
INSERT INTO anime VALUES('35', 'Kono Naka ni Hitori Imouto ga Iru ', '12', '2012', 'Harem Romance', '1', '25', 'Internet', 'non', 'non', 'Kono Naka ni Hitori, Imouto ga Iru !.jpg', '');
INSERT INTO anime VALUES('36', 'Kore wa Zombie Desu ka ?', '26', '2011', 'Surnaturel Romance', '2', '25', 'Internet', 'non', 'non', 'Kore wa Zombie Desu ka.jpg', '');
INSERT INTO anime VALUES('37', 'Steel Angel Kurumi', '24', '1999', 'Surnaturel Romance', '1', '12', 'Internet', 'non', 'non', 'Koutetsu Tenshi Kurumi.jpg', '');
INSERT INTO anime VALUES('38', 'Kurenai', '12', '2008', 'Action Romance', '1', '25', 'Internet', 'non', 'non', 'Kurenai.jpg', '');
INSERT INTO anime VALUES('39', 'Mahoraba : Heartful Days', '26', '2001', 'Comedie Romance', '1', '25', 'Internet', 'non', 'non', 'Mahoraba Heartful Days.jpg', '');
INSERT INTO anime VALUES('40', 'Mashiro-Iro Symphony', '12', '2011', 'Romance Vie Scolaire', '1', '25', 'Internet', 'non', 'non', 'Mashiro Iro Symphony.jpg', '');
INSERT INTO anime VALUES('41', 'Onegai twins', '12', '2003', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'onegaitwins.jpg', '');
INSERT INTO anime VALUES('42', 'Onii-chan Dakedo', '12', '2012', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Onii-chan Dakedo.jpg', '');
INSERT INTO anime VALUES('43', 'Ore no Kanojo', '13', '2013', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Ore no Kanojo.jpg', '');
INSERT INTO anime VALUES('44', 'Papa no Iu Koto wo Kikinasai !', '12', '2012', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'papa-no-iukoto-wo-kikinasai.jpg', '');
INSERT INTO anime VALUES('45', 'Phantom Requiem', '26', '2009', 'Romance Gangster', '1', '25', 'Internet', 'non', 'non', 'Phantom Requiem.jpg', '');
INSERT INTO anime VALUES('46', 'Rokujouma no Shinryakusha!?', '12', '2014', 'Romance Surnaturel Harem', '1', '25', 'Internet', 'non', 'non', 'Rokujouma no Shinryakusha.jpg', '');
INSERT INTO anime VALUES('47', 'Rosario Vampire', '26', '2008', 'Harem Surnaturel', '2', '25', 'Internet', 'non', 'non', 'Rosario Vampire.jpg', '');
INSERT INTO anime VALUES('48', 'Seikon no Qwaser', '26', '2010', 'Action Romance', '2', '25', 'Internet', 'non', 'non', 'Seikon no Qwaser.jpg', '');
INSERT INTO anime VALUES('49', 'Shakugan no Shana', '62', '2005', 'Suraturel Romance', '3', '25', 'Internet', 'non', 'non', 'Shakugan no Shana.jpg', '');
INSERT INTO anime VALUES('50', 'Sister Princess', '26', '2001', 'Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Sister Princess.jpg', '');
INSERT INTO anime VALUES('51', 'Sola', '13', '2007', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Sola.jpg', '');
INSERT INTO anime VALUES('52', 'Tactical roar', '13', '2006', 'Romance Armee', '1', '25', 'PC', 'non', 'non', 'Tactical roar.jpg', '');
INSERT INTO anime VALUES('53', 'Tayutama -Kiss on my Deity-', '12', '2009', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Tayutama Kiss on my Deity.png', '');
INSERT INTO anime VALUES('54', 'Tenshi ni Narumon !', '26', '1999', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Tenshi ni Narumon.jpg', '');
INSERT INTO anime VALUES('55', 'Vampire Knight', '26', '2008', 'Romance Surnaturel', '2', '25', 'Internet', 'non', 'non', 'Vampire Knight.jpg', '');
INSERT INTO anime VALUES('56', 'Zero no Tsukaima', '48', '2006', 'Surnaturel Harem Romance', '4', '25', 'Internet', 'non', 'non', 'Zero no Tsukaima.png', '');
INSERT INTO anime VALUES('57', 'Witchcraft Works', '12', '2014', 'Sunaturel Romance Comedie', '1', '25', 'PC', 'non', 'non', 'witchcraft_works.jpg', '');
INSERT INTO anime VALUES('58', 'Tasogare Otome x Amnesia', '12', '2012', 'Romance Surnaturel', '1', '25', 'PC', 'non', 'non', 'Tasogare Otome x Amnesia.jpg', '');
INSERT INTO anime VALUES('59', 'Sword Art Online', '49', '2012', 'Jeux Romance', '2', '25', 'PC', 'non', 'non', 'Sword Art Online.jpg', '');
INSERT INTO anime VALUES('60', 'Strike the blood', '26', '2013', 'Harem Surnaturel Romance', '2', '25', 'PC', 'non', 'non', 'Strike the blood.jpg', '');
INSERT INTO anime VALUES('61', 'Tokyo Ravens', '24', '2013', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Tokyo Ravens.jpg', '');
INSERT INTO anime VALUES('62', 'Yosuga no Sora', '12', '2010', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Yosuga no Sora.jpg', '');
INSERT INTO anime VALUES('63', 'Shuffle!', '25', '2005', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Shuffle!.jpg', '');
INSERT INTO anime VALUES('64', 'Sekirei', '26', '2008', 'Ecchi Harem Romance', '2', '25', 'PC', 'non', 'non', 'sekirei.jpg', '');
INSERT INTO anime VALUES('65', 'Shingetsutan Tsukihime', '12', '2003', 'Surnaturel Romance', '1', '25', 'PC', 'non', 'non', 'Shingetsutan Tsukihime.jpg', '');
INSERT INTO anime VALUES('66', 'Rental Magica', '24', '2007', 'Harem Surnaturel', '1', '25', 'PC', 'non', 'non', 'Rental Magica.jpg', '');
INSERT INTO anime VALUES('67', 'Saenai Heroine no Sodatekata', '13', '2015', 'Romance Manga', '1', '25', 'Internet', 'non', 'non', 'Saenai Heroine no Sodatekata.jpg', '');
INSERT INTO anime VALUES('68', 'Sakurasou no Pet na Kanojo', '24', '2012', 'Romance Tranche de Vie', '1', '25', 'PC', 'non', 'non', 'Sakurasou no Pet na Kanojo.jpg', '');
INSERT INTO anime VALUES('69', 'Outbreak Company', '12', '2013', 'Romance Surnaturel Harem', '1', '25', 'Internet', 'non', 'non', 'Outbreak Company.jpg', '');
INSERT INTO anime VALUES('70', 'Photo Kano', '13', '2016', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Photo Kano.jpg', '');
INSERT INTO anime VALUES('71', 'Princess Lover', '12', '2009', 'Romance Tranche de Vie', '1', '25', 'PC', 'non', 'non', 'Princess Lover.jpg', '');
INSERT INTO anime VALUES('72', 'Nogizaka Haruka no Himitsu', '28', '2008', 'Romance Tranche de Vie', '3', '25', 'PC', 'non', 'non', 'Nogizaka Haruka no Himitsu.jpg', '');
INSERT INTO anime VALUES('73', 'Oda Nobuna no Yabou', '12', '2012', 'Romance Action', '1', '25', 'PC', 'non', 'non', 'Oda Nobuna no Yabou.jpg', '');
INSERT INTO anime VALUES('74', 'Omamori Himari', '12', '2010', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'Omamori Himari.jpg', '');
INSERT INTO anime VALUES('75', 'Onegai Teacher', '12', '2002', 'Romance Surnaturel', '1', '25', 'PC', 'non', 'non', 'OnegaiTeacher.jpg', '');
INSERT INTO anime VALUES('76', 'Myself ; Yourself', '13', '2007', 'Romance Drame', '01', '25', 'Internet', 'non', 'non', 'Myself Yourself.jpg', '');
INSERT INTO anime VALUES('77', 'Nagasarete Airantou', '26', '2007', 'Romance Comedie', '1', '25', 'Internet', 'non', 'non', 'Nagasarete Airantou.jpg', '');
INSERT INTO anime VALUES('78', 'No-Rin', '12', '2014', 'Agriculture Romance', '1', '25', 'Internet', 'non', 'non', 'No Rin.jpg', '');
INSERT INTO anime VALUES('79', 'Mamoru-kun', '24', '2006', 'Romance Magie', '1', '25', 'PC', 'non', 'non', 'Mamoru kun.jpg', '');
INSERT INTO anime VALUES('80', 'Madan no Ou to Vanadis', '13', '2014', 'Romance Aventure', '1', '25', 'PC', 'non', 'non', 'Madan no Ou to Vanadis.jpg', '');
INSERT INTO anime VALUES('81', 'Kimi ga Aruji de Shitsuji ga Ore de', '13', '2008', 'Romance Tranche de Vie Comedie', '1', '25', 'PC', 'non', 'non', 'Kimi ga Aruji de Shitsuji ga Ore de.jpg', '');
INSERT INTO anime VALUES('82', 'Kanojo ga Flag wo Oraretara', '12', '2014', 'Comedie Romance', '1', '25', 'Internet', 'non', 'non', 'Kanojo ga Flag wo Oraretara.jpg', '');
INSERT INTO anime VALUES('83', 'IS : Infinite Stratos ', '26', '2011', 'Romance Mecha', '2', '25', 'PC', 'non', 'non', 'IS.jpg', '');
INSERT INTO anime VALUES('84', 'Iscuca', '10', '2015', 'Surnaturel Romance', '1', '25', 'Internet', 'non', 'non', 'isuca.png', '');
INSERT INTO anime VALUES('85', 'High School DxD', '36', '2012', 'Surnaturel Harem Ecchi', '3', '25', 'PC', 'non', 'non', 'high-school-dxd.jpg', '');
INSERT INTO anime VALUES('86', 'Monsieur est Servie', '12', '2004', 'Romance Comedie', '1', '12', 'PC', 'non', 'non', 'Monsieur est Servie.jpg', '');
INSERT INTO anime VALUES('87', 'Happy Lesson', '28', '2001', 'Comedie Romance', '3', '25', 'Internet', 'non', 'non', 'Happy Lesson.jpg', '');
INSERT INTO anime VALUES('88', 'Golden Time', '24', '2013', 'Romance Drame Tranche de Vie', '1', '25', 'PC', 'non', 'non', 'Golden Time.jpg', '');
INSERT INTO anime VALUES('89', 'Fate/Stay Night ', '24', '2006', 'Romance Surnaturel', '1', '25', 'Internet', 'non', 'non', 'Fate Stay Night.jpg', '');
INSERT INTO anime VALUES('90', 'Fortune Arterial', '12', '2010', 'Romance Surnaturel', '1', '25', 'Internet', 'non', 'non', 'Fortune_Arterial.jpg', '');
INSERT INTO anime VALUES('91', 'Freezing', '26', '2011', 'Action Ecchi Romance', '2', '25', 'Internet', 'non', 'non', 'Freezing.jpg', '');
INSERT INTO anime VALUES('92', 'Futakoi', '13', '2004', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Futakoi.jpg', '');
INSERT INTO anime VALUES('93', 'Clannad', '23', '2007', 'Romance Drame', '1', '25', 'Internet', 'non', 'non', 'Clannad.jpg', '');
INSERT INTO anime VALUES('94', 'D-Fragments', '12', '2014', 'Romance Comedie', '1', '25', 'Internet', 'non', 'non', 'D-Fragments.png', '');
INSERT INTO anime VALUES('95', 'Dakara boku wa, H ga Dekinai', '12', '2012', 'Romance Ecchi Surnaturel', '1', '25', 'Internet', 'non', 'non', 'Dakara-Boku-wa-H-ga-Dekinai.jpg', '');
INSERT INTO anime VALUES('96', 'Dance In The Vampire Bund', '12', '2010', 'Romance Surnaturel', '1', '25', 'Internet', 'non', 'non', 'Dance In The Vampire Bund.jpg', '');
INSERT INTO anime VALUES('97', 'Campione !', '13', '2012', 'Romance Surnaturel', '1', '25', 'PC', 'non', 'non', 'Campione !.jpg', '');
INSERT INTO anime VALUES('98', 'Boku wa Tomodachi ga Sukunai', '24', '2011', 'Romance Tranche de Vie', '2', '25', 'Internet', 'non', 'non', 'Boku wa Tomodachi ga Sukunai.jpg', '');
INSERT INTO anime VALUES('99', 'Bokura wa Minna Kawaisou', '12', '2014', 'Romance Comedie', '1', '25', 'PC', 'non', 'non', 'Bokura wa Minna Kawaisou.jpg', '');
INSERT INTO anime VALUES('100', 'Amagami SS', '28', '2010', 'Romance', '2', '25', 'PC', 'non', 'non', 'amagami_ss.jpg', '');
INSERT INTO anime VALUES('101', 'Absolute Duo', '12', '2015', 'Action Romance Harem', '1', '25', 'PC', 'non', 'non', 'absolute.jpg', '');
INSERT INTO anime VALUES('102', 'Ah! My Goddess', '52', '2005', 'Romance Surnaturel', '2', '25', 'PC', 'non', 'non', 'ah_my_goddess.jpg', '');
INSERT INTO anime VALUES('103', 'Ai Yori Aoshi', '37', '2002', 'Romance Tranche de Vie', '2', '25', 'PC', 'non', 'non', 'Ai-Yori-Aoshi.jpg', '');
INSERT INTO anime VALUES('104', 'Aishiteruze baby', '26', '2004', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Aishiteruze baby.jpg', '');
INSERT INTO anime VALUES('105', 'Yoake mae yori ruri iro na', '12', '2006', 'Romance', '1', '25', 'Internet', 'non', 'non', 'Yoake mae yori ruri iro na.jpg', '');
INSERT INTO anime VALUES('106', 'Daitoshokan no Hitsujikai', '12', '2014', 'Romance Tranche de Vie', '1', '25', 'Internet', 'non', 'non', 'Daitoshokan no Hitsujikai.jpg', '');
INSERT INTO anime VALUES('107', 'Chobits', '26', '2002', 'Romance Mecha', '1', '25', 'Internet', 'non', 'non', 'chobits.png', '');
INSERT INTO anime VALUES('108', 'Evangelion The End', '1', '1998', 'Mecha Psychologique', '1', '1h30', 'PC', 'non', 'oui', 'evangelion.jpg', '');
INSERT INTO anime VALUES('109', 'Dragon Ball Z Battle of Gods', '1', '2013', 'Action Arts Martiaux', '1', '1h25', 'PC', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('110', 'Kiss x Sis', '12', '2009', 'Romance Ecchi', '1', '25', 'PC', 'oui', 'non', 'kiss-x-sis.jpg', '');
INSERT INTO anime VALUES('111', 'Kanokon', '2', '2009', 'Surnaturel Romance Ecchi', '1', '25', 'PC', 'oui', 'non', 'kanokon.jpg', '');
INSERT INTO anime VALUES('112', 'Full Metal Achemist Shambala', '1', '2003', 'Science Fantaisie Action', '1', '1h40', 'PC', 'non', 'oui', 'FullmetalAlchemist.png', '');
INSERT INTO anime VALUES('113', 'Guilty Crown', '1', '2012', 'Surnaturel Romance', '1', '25', 'Internet', 'oui', 'non', 'Guilty Crown.jpg', '');
INSERT INTO anime VALUES('114', 'Onegai Twins', '1', '2004', 'Romance Tranche de Vie', '1', '25', 'Internet', 'oui', 'non', 'onegaitwins.jpg', '');
INSERT INTO anime VALUES('115', 'Papa no Iu Koto wo Kikinasai', '2', '2013', 'Romance Tranche de Vie', '1', '25', 'Internet', 'oui', 'non', 'papa-no-iukoto-wo-kikinasai.jpg', '');
INSERT INTO anime VALUES('116', 'Witchcraft Works', '1', '2015', 'Surnaturel Romance Comedie', '1', '25', 'PC', 'oui', 'non', 'witchcraft_works.jpg', '');
INSERT INTO anime VALUES('117', 'Tasogare Otome x Amnesia', '1', '2013', 'Romance Surnaturel', '1', '25', 'PC', 'oui', 'non', 'Tasogare Otome x Amnesia.jpg', '');
INSERT INTO anime VALUES('118', 'Sekirei', '2', '2009', 'Ecchi Romance Harem', '1', '25', 'PC', 'oui', 'non', 'sekirei.jpg', '');
INSERT INTO anime VALUES('119', 'Onegai Teacher', '1', '2003', 'Romance Surnaturel', '1', '25', 'PC', 'oui', 'non', 'OnegaiTeacher.jpg', '');
INSERT INTO anime VALUES('120', 'IS : Infinite Stratos', '2', '2014', 'Romance Mecha', '1', '50', 'PC', 'oui', 'non', 'IS.jpg', '');
INSERT INTO anime VALUES('121', 'Fortune Arterial', '1', '2011', 'Romance Surnaturel', '1', '25', 'Internet', 'oui', 'non', 'Fortune_Arterial.jpg', '');
INSERT INTO anime VALUES('122', 'Clannad', '2', '2008', 'Romance Drame', '1', '25', 'Internet', 'oui', 'non', 'Clannad.jpg', '');
INSERT INTO anime VALUES('123', 'Dakara boku wa, H ga Dekinai', '1', '2013', 'Romance Ecchi Surnaturel', '1', '25', 'Internet', 'oui', 'non', 'Dakara-Boku-wa-H-ga-Dekinai.jpg', '');
INSERT INTO anime VALUES('124', 'Bokura wa Minna Kawaisou', '1', '2015', 'Romance Comedie', '1', '30', 'PC', 'oui', 'non', 'Bokura wa Minna Kawaisou.jpg', '');
INSERT INTO anime VALUES('125', 'Amagami SS', '6', '2011', 'Romance', '1', '6', 'PC', 'oui', 'non', 'amagami_ss.jpg', '');
INSERT INTO anime VALUES('126', 'Kanojo ga Flag wo Oraretara', '1', '2014', 'Comedie Romance', '1', '25', 'Internet', 'oui', 'non', 'Kanojo ga Flag wo Oraretara.jpg', '');
INSERT INTO anime VALUES('127', 'Final Approch', '13', '2004', 'Comedie Romance', '1', '12', 'Internet', 'non', 'non', 'Final Approch.jpg', '');
INSERT INTO anime VALUES('128', 'Uragiri', '24', '2010', 'Fantastique Shonen-Ai', '2', '25', 'PC', 'non', 'non', 'Uragiri.jpg', '');
INSERT INTO anime VALUES('129', 'Shinrei Tantei Yakumo', '13', '2010', 'Policier Fantastique', '1', '25', 'PC', 'non', 'non', 'Shinrei Tantei Yakumo.jpg', '');
INSERT INTO anime VALUES('130', 'Dragon Ball Z Bio Broly', '1', '1994', 'Action Arts Martiaux', '1', '45', 'PC', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('131', 'Dragon Ball Z Broly', '1', '1993', 'Action Arts Martiaux', '1', '45', 'PC', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('132', 'Dragon Ball Z 100 milles Guerriers de metal', '1', '1992', 'Action Arts Martiaux', '1', '45', 'CD', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('133', 'Dragon Ball Z : Fusion', '1', '1995', 'Action Arts Martiaux', '1', '45', 'PC', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('134', 'Dragon Ball Z : La Revanche de Cooler', '1', '1991', 'Action Arts Martiaux', '1', '45', 'CD', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('135', 'Dragon Ball Z : Le Combat fratricide', '1', '1990', 'Action Arts Martiaux', '1', '45', 'CD', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('136', 'Dragon Ball Z Le retour de Broly', '1', '1994', 'Action Arts Martiaux', '1', '45', 'PC', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('137', 'Dragon Ball Z : Le Pere de Sangoku', '1', '1990', 'Action Arts Martiaux', '1', '45', 'CD', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('138', 'Dragon Ball Z : L Histoire de Trunks', '1', '1993', 'Action Arts Martiaux', '1', '45', 'Internet', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('139', 'Sola', '2', '2008', 'Surnaturel Romance', '1', '25', 'Internet', 'oui', 'non', 'Sola.jpg', '');
INSERT INTO anime VALUES('140', 'Full Metal Achemist', '3', '2001', 'Science Fantaisie Action', '1', '25', 'PC', 'oui', 'non', 'FullmetalAlchemist.png', '');
INSERT INTO anime VALUES('141', 'Naruto La Mort de Naruto', '1', '2007', 'Action Aventure', '1', '1h35', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('142', 'Naruto Les Liens', '1', '2008', 'Action Aventure', '1', '1h30', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('143', 'Naruto La volonte du Feu', '1', '2009', 'Action Aventure', '1', '1h35', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('144', 'Naruto La tour perdue', '1', '2010', 'Action Aventure', '1', '1h25', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('145', 'Naruto Prison Sanglante', '1', '2011', 'Action Aventure', '1', '1h34', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('146', 'Naruto Road to Ninja', '1', '2013', 'Action Aventure', '1', '1h50', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('148', 'Saint Seiya Lost Canvas', '26', '2010', 'Action Mythologie', '2', '25', 'PC', 'non', 'non', 'Saint_Seiya_The_Lost_Canvas.jpg', '');
INSERT INTO anime VALUES('149', 'Dragon Ball Gt', '64', '1996', 'Action Arts Martiaux', '1', '25', 'Internet', 'non', 'non', 'DragonBallGt.jpg', '');
INSERT INTO anime VALUES('150', 'Naruto Shippuden', '500', '2007', 'Action Aventure', '22', '25', 'PC', 'non', 'non', 'naruto.png', '');
INSERT INTO anime VALUES('151', 'Naruto', '82', '2006', 'Action Aventure', '1', '25', 'Internet', 'oui', 'non', 'naruto.png', '');
INSERT INTO anime VALUES('152', 'High School DxD', '3', '2013', 'Surnaturel Harem Ecchi', '1', '25', 'PC', 'oui', 'non', 'high-school-dxd.jpg', '');
INSERT INTO anime VALUES('153', 'Bleach', '366', '2001', 'Fantome, combat au sabre', '1', '25', 'Internet', 'non', 'non', 'bleach.jpg', '');
INSERT INTO anime VALUES('154', 'Kodomo No Jikan', '12', '2007', 'Drame Ecchi Romance', '1', '25', 'Internet', 'non', 'non', 'Kodomo No Jikan.jpg', '');
INSERT INTO anime VALUES('155', 'Kono Naka ni Hitori, Imouto ga Iru !', '1', '2012', 'Romance Harem', '1', '25', 'Internet', 'oui', 'non', 'Kono Naka ni Hitori, Imouto ga Iru !.jpg', '');
INSERT INTO anime VALUES('156', 'Saint Seiya Hades', '31', '2002', 'Action Mythologie', '3', '25', 'PC', 'non', 'non', 'saint seiya.jpg', '');
INSERT INTO anime VALUES('157', 'Saint Seiya Abrege', '13', '2003', 'Action Mythologie Comedie', '1', '12', 'PC', 'non', 'non', 'saint seiya.jpg', '');
INSERT INTO anime VALUES('158', 'Saint Seiya Legend of Sanctuary', '1', '2015', 'Action Mythologie', '1', '1h32', 'PC', 'non', 'oui', 'SaintSeiyaLegendofSanctuary.jpg', '');
INSERT INTO anime VALUES('159', 'Albator Corsaire de L espace', '1', '2014', 'Action Aventure', '1', '1h40', 'PC', 'non', 'oui', 'albator.jpg', '');
INSERT INTO anime VALUES('160', 'Naruto The Last Movie', '1', '2014', 'Action Aventure', '1', '1h50', 'PC', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('161', 'Mayoi Neko Overrun!', '13', '2010', 'Comedie Romance Harem', '1', '25', 'Internet', 'non', 'non', 'Mayoi Neko Overrun!.jpg', '');
INSERT INTO anime VALUES('162', 'Aikikan', '12', '2009', 'Romance Echii Comedie', '1', '25', 'Internet', 'non', 'non', 'Akikan.jpg', '');
INSERT INTO anime VALUES('163', 'Plastic Memoiries', '13', '2015', 'Romance Drame Sciences-Fiction', '1', '25', 'Internet', 'non', 'non', 'Plastic Memoiries.jpg', '');
INSERT INTO anime VALUES('164', 'Dungeon ni Deai', '13', '2015', 'Romance Aventure', '1', '25', 'PC', 'non', 'non', 'Dungeon ni Deai.jpg', '');
INSERT INTO anime VALUES('165', 'Noragami', '12', '2014', 'Romance Surnaturel Action', '1', '25', 'Internet', 'non', 'non', 'Noragami.jpg', '');
INSERT INTO anime VALUES('166', 'Monster Musume', '12', '2015', 'Comedie Romance Harem', '1', '25', 'PC', 'non', 'non', 'Monster Musume.jpg', '');
INSERT INTO anime VALUES('167', 'Dragon Ball Super', '90', '2015', 'Action Aventure', '5', '25', 'PC', 'non', 'non', 'dragon ball super.jpg', '2017-05-19 11:21:30.0');
INSERT INTO anime VALUES('168', 'Mamotte Shugogetten', '22', '1998', 'Comedie Romance Magical Girl', '1', '25', 'Internet', 'non', 'non', 'Mamotte Shugogetten.jpg', '');
INSERT INTO anime VALUES('169', 'Samourai Pizza Cats', '52', '1990', 'Comedie Robot Action', '1', '25', 'DVD', 'non', 'non', 'Samourai Pizza Cats.png', '');
INSERT INTO anime VALUES('170', 'Unbeakable Machine Doll', '12', '2013', 'Fantastique Harem Romance', '1', '25', 'PC', 'non', 'non', 'Unbeakable Machine Doll.jpg', '');
INSERT INTO anime VALUES('171', 'Dragon Ball Z Fukkatsu F', '1', '2015', 'Action Arts Martiaux', '1', '1h30', 'PC', 'non', 'oui', 'dragon ball z.png', '');
INSERT INTO anime VALUES('172', 'Rakudai Kishi no Cavalry', '12', '2015', 'Surnaturel Romance Aventure', '1', '25', 'PC', 'non', 'non', 'Rakudai Kishi no Cavalry.jpg', '');
INSERT INTO anime VALUES('173', 'Sakurako-san no Ashimoto', '12', '2015', 'Mystere', '1', '25', 'PC', 'non', 'non', 'sakurako-san.jpg', '');
INSERT INTO anime VALUES('174', 'Iscuca', '1', '2015', 'Surnaturel Romance', '1', '25', 'Internet', 'oui', 'non', 'isuca.png', '');
INSERT INTO anime VALUES('175', 'Baby Steps', '50', '2014', 'Sports Romance', '2', '25', 'PC', 'non', 'non', 'baby.jpg', '');
INSERT INTO anime VALUES('176', 'Shoujo Tachi', '12', '2016', 'Comedie Romance Tranche de Vie', '1', '25', 'PC', 'non', 'non', 'Shoujo Tachi.jpg', '');
INSERT INTO anime VALUES('177', 'D Gray Man', '116', '2006', 'Aventure Horreur Action', '3', '25', 'PC', 'non', 'non', 'd gray man.jpg', '');
INSERT INTO anime VALUES('178', 'Naruto : Boruto', '1', '2015', 'Action Aventre', '1', '1h50', 'Internet', 'non', 'oui', 'naruto.png', '');
INSERT INTO anime VALUES('179', 'Kuroko no Basket', '75', '2012', 'Sport', '3', '25', 'PC', 'non', 'non', 'kuroko_no_basket.jpg', '');
INSERT INTO anime VALUES('180', 'Kuroko no Basket', '3', '2014', 'Sport Ecole', '1', '25', 'PC', 'oui', 'non', 'kuroko_no_basket.jpg', '');
INSERT INTO anime VALUES('181', 'Hundred', '12', '2016', 'Action Romance Harem', '1', '25', 'PC', 'non', 'non', 'hundred.jpg', '');
INSERT INTO anime VALUES('182', 'Netoge no Yome wa Onnanoko ja Nai to Omotta', '12', '2016', 'Ecchi Romance', '1', '25', 'PC', 'non', 'non', 'Netoge no Yome wa Onnanoko ja Nai to Omotta.png', '');
INSERT INTO anime VALUES('183', 'Majikoi', '12', '2011', 'Action Romance Harem', '1', '25', 'PC', 'non', 'non', 'majikoi.jpg', '');
INSERT INTO anime VALUES('184', 'Amamma to Inazuma', '12', '2016', 'Comedie Tranche de Vie', '1', '25', 'PC', 'non', 'non', 'amamma.jpg', '');
INSERT INTO anime VALUES('185', 'Orange', '13', '2016', 'Comedie Romance Drame', '1', '25', 'PC', 'non', 'non', 'orange.jpg', '');
INSERT INTO anime VALUES('188', 'Days', '24', '2016', 'Comedie Sport', '1', '25', 'PC', 'non', 'non', 'days.jpg', '');
INSERT INTO anime VALUES('189', 'Dungeon ni Deai', '1', '2016', 'Romance Aventure', '1', '25', 'PC', 'oui', 'non', 'Dungeon ni Deai.jpg', '');
INSERT INTO anime VALUES('190', 'Tales of Zestiria the X', '25', '2013', 'Action Surnaturel', '2', '25', 'PC', 'non', 'non', 'tales.jpg', '2017-04-30 11:38:49.0');
INSERT INTO anime VALUES('191', 'Ah my goddess', '5', '2007', 'Romance Surnaturel', '1', '25', 'PC', 'oui', 'non', 'ah_my_goddess.jpg', '');
INSERT INTO anime VALUES('192', 'Onee Chan ga Kita', '13', '2014', 'Comedie Romance', '1', '3', 'PC', 'non', 'non', 'onee.jpg', '');
INSERT INTO anime VALUES('196', 'Seiren', '12', '2017', 'Comedie Harem Romance', '1', '25', 'PC', 'non', 'non', 'seiren.jpg', '');
INSERT INTO anime VALUES('197', '3 Gatsu no lion', '22', '2017', 'Comedie Drame Shogie', '1', '25', 'PC', 'non', 'non', '3 gatsu no lion.jpg', '');
INSERT INTO anime VALUES('198', 'Full Metal Alchemist Brotherhood', '64', '2009', 'Aventure Fantasy Surnaturel', '1', '25', 'PC', 'non', 'non', 'FullmetalAlchemist.png', '');
INSERT INTO anime VALUES('199', 'Kuzu no Honkai', '12', '2017', 'Drame Romance Tranche de Vie', '1', '25', 'PC', 'non', 'non', 'kuzu_no_honkai.jpg', '');
INSERT INTO anime VALUES('200', 'Kono Subarischi', '10', '2016', 'Comedie Action Surnaturel', '1', '25', 'PC', 'non', 'non', 'kono.jpg', '2017-04-16 08:42:13.0');
INSERT INTO anime VALUES('201', 'Kono Subaraschi', '1', '1', 'Comedie Action Sunaturel', '1', '25', 'PC', 'oui', 'non', 'kono.jpg', '2017-04-16 08:42:22.0');
INSERT INTO anime VALUES('202', 'Re Creators', '5', '2017', 'Enigme Science Fiction', '1', '25', 'PC', 'non', 'non', 'recreators.jpeg', '2017-05-09 16:35:00.0');
INSERT INTO anime VALUES('203', 'Eureka Seven', '31', '2005', 'Mecha Romance', '1', '25', 'Internet', 'non', 'non', 'eureka.jpg', '2017-04-19 15:41:43.0');
INSERT INTO anime VALUES('204', 'Arslan Senki', '17', '2015', 'Action Aventure', '1', '25', 'PC', 'non', 'non', 'arslan senki.jpg', '2017-05-13 07:55:45.0');

-- -----------------------------
-- insertions dans la table manga
-- -----------------------------
INSERT INTO manga VALUES('1', 'Dragon Ball Z', '42', '519', '1989', 'Shonen', 'Termine', ' 	Action', 'Dragon Ball Z se deroule cinq ans apres le mariage de Son Goku et de Chichi. Raditz, un mysterieux guerrier de l espace, frere de Son Goku, arrive sur Terre pour retrouver Goku. Ce dernier apprend qu il vient d une planete de guerriers redoutables dont il ne reste plus que quatre survivants.', 'Acheter');
INSERT INTO manga VALUES('2', 'Death Note', '13', '110', '2006', 'Shonen', 'Termine', 'Policier,Thriller, Psychlogique', 'Light Yagami est un lyceen surdoue qui juge le monde actuel criminel et corrompu. Sa vie change du tout au tout le jour ou il ramasse par hasard un mysterieux cahier intitule Death Note. Le mode d emploi inclus dans le cahier indique que la personne dont le nom est inscrit dans ce carnet meurt. D abord sceptique, Light teste le carnet et decouvre que son pouvoir est bien reel. Il rencontre l ancien proprietaire du Death Note, un dieu de la mort nomme Ryuk. Celui-ci declare avoir volontairement laisse tomber son carnet dans le but de se divertir.Light decide d utiliser le Death Note pour exterminer les criminels, dans le but d eradiquer le Mal et de batir un monde parfait dont il sera le dieu. Il apprend peu a peu a se servir des pouvoirs du cahier.', 'Acheter');
INSERT INTO manga VALUES('3', 'Dusk of Amnesia', '10', '47', '2009', 'Shonen', 'Termine', 'Romance, Surnaturel', 'L ecole privee Seikyo est connue pour ses nombreuses histoires d epouvante, mais une legende reste particulierement ancree dans l histoire de l etablissement : en raison d une malediction, une etudiante aurait ete enfermee dans le campus et son fantome le hanterait encore aujourd hui. Alors qu il vient tout juste d integrer l ecole, Teiichi Niiya tombe nez a nez avec le spectre, se nommant Yuko Kanoe, une ravissante jeune fille qui a oublie son passe. Pique par la curiosite et se retrouvant hante par Yuko, Teiichi integre le club d investigation des activites paranormales dont elle est la presidente et decide d enqueter afin de mettre en lumiere le mystere qui entoure sa mort.', 'Acheter');
INSERT INTO manga VALUES('4', 'WitchCraft Works', '11', '57', '2010', 'Seinen', 'En Cours', ' Aventure,Fantastique', 'Dans un monde ou cohabitent humains et sorcieres, l apocalypse est annoncee. L histoire est centree autour de Honoka Takamiya, un lyceen ordinaire dont sa camarade de classe, Ayaka Kagari, excelle dans tous les domaines (sports, etudes, arts, beaute).Un jour, Takamiya se retrouve en danger et c est alors qu il decouvre que Ayaka est l une des sorcieres les plus puissantes sur Terre...', 'Acheter');
INSERT INTO manga VALUES('5', 'Black Lagoon', '10', '87', '2002', 'Seinen', 'Termine', 'Action,Aventure,Gangster', 'Rokuro Okajima, jeune employe d une grande entreprise, est charge de voyager sur les mers d Asie du Sud-Est pour livrer un disque contenant des donnees secretes et capitales sur la societe pour laquelle il travaille. Malheureusement, son bateau se fait attaquer par une bande de pirates free-lance voulant recuperer son bien et lui-m?me sera pris en otage sur leur bateau, le Black Lagoon, un vieux torpilleur.
Pensant que sa compagnie va tout mettre en ?uvre pour le secourir, il ne s inqui?te pas outre mesure. Ce qu il ignore, c est que ses superieurs ont engage des mercenaires pour le faire taire et detruire toutes les preuves de l existence du disque?il d?cide d abandonner sa vie au Japon pour rejoindre l aventure de ces pirates des temps modernes.', 'Telecharger/Acheter');
INSERT INTO manga VALUES('6', 'High School DxD', '9', '58', '2008', 'Ecchi', 'En Pause', 'Harem,Ecchi,Surnaturel', 'Issei Hyodo est un etudiant de seconde annee qui a une enorme dependance au sexe. Il vit une vie tranquille jusqu a un rendez-vous avec une fille nommee Yuma. A la fin de celui-ci, Issei est emmene dans un petit parc et Yuma lui demande s il veut lui realiser son souhait. Croyant recevoir un baiser de la jeune fille, Issei est choque lorsque Yuma lui souffle les mots Peux-tu mourir pour moi ? et se transforme en ange dechu. Le garcon est brutalement attaque et tue par Yuma. Issei se reveille le lendemain matin, croyant a un reve. Par la suite, il remarque Rias Gremory, etudiante de troisieme annee de son lycee, nue dans son lit. Elle revele son identite de demon a Issei et dit qu elle l a egalement reincarne en demon, devant lui servir d esclave ainsi qu a la famille Gremory.', 'Acheter');
INSERT INTO manga VALUES('7', 'Cimoc', '5', '20', '2011', 'Seinen', 'Termine', 'Comedie,Romance,Ecchi', 'Kota Inamine debarque a Tokyo pour realiser son reve : devenir mangaka. Mais ses premieres planches ne sont guere appreciees et ses jobs d assistant-dessinateur finissent en fiasco. Alors que Kota plonge dans le desespoir, il apprend que son envahissante voisine est aussi redactrice en chef d un magazine de manga ! La roue du destin va-t-elle enfin commencer a tourner pour Kota ? Deviendra-t-il un grand mangaka ?', 'Acheter');
INSERT INTO manga VALUES('8', 'xxxHolic Rei', '4', '52', '2013', 'Seinen', 'En Cours', 'Magie,Drame,Tranche de vie', 'Watanuki, un lyceen capable de voir les esprits et Yuko, une mysterieuse sorciere, sont de retour dans une nouvelle histoire, entre reve et realite. Une jolie femme trouve l entree de la boutique de Yuko, guidee par une force obscure. De quel mal souffre-t-elle et quel est son souhait ? Entrez dans le monde fantastique et chimerique de XXXHolic !', 'Acheter');
INSERT INTO manga VALUES('9', 'Phantom Pain', '6', '36', '2011', 'Shonen', 'Termine', 'Action,Fantastique', 'Il y a pres d un siecle, une civilisation florissante de mages mettait a nu des ruines tres anciennes entrainant l engloutissement de la moitie de la planete sous les eaux. L une des consequences funestes de cet evenement est l apparition de spectres capables de prendre possession des corps des defunts si ceux-ci n ont pas ete benis prealablement par la toute puissante Eglise. Un pretre deserteur, Koji, et Matelia, une jeune femme mi-demon mi-humaine, defient alors l organisation ecclesiastique en venant en aide aux plus demunis, aux heretiques et a tout ceux refusant la dictature religieuse. Mais quels sombres secrets se cachent derriere leur collaboration et leurs pouvoirs ?', 'Acheter');
INSERT INTO manga VALUES('10', 'Phantom King', '7', '28', '2009', 'Seinen', 'Termine', 'Horreur, Ecchi, Action', 'Il y a 11 ans, dans la petite ville de Youngda, des demons seraient apparus et auraient aneanti la quasi totalite de la population. On se rappelle de cette tragedie comme le Jour du Diable. Aujourd hui, de nouveaux phenomenes inexpliques font leur apparition et le nombre de morts ne cesse d augmenter. Une organisation secrete cherche a faire front en recrutant des personnes au potentiel exceptionnel. Parmi eux, une personne se dressera et mettra un terme a la terreur : le Phantom King !', 'Acheter/Lu Anglais');
INSERT INTO manga VALUES('11', 'Blue Exorcist', '19', '88', '2009', 'Shonen', 'En Cours', 'Suspense, Fantastique, Aventure', 'Adopte des son plus jeune age par un exorciste de renom, Rin apprend un jour qu il est le fils du mal incarne, quand son veritable pere, Satan lui-meme, apparait pour l emmener dans son monde. Mais impossible pour le jeune homme d oublier tout ce qui lui a ete enseigne jusqu ici Confronte a un adversaire invincible qui a consume le seul homme a l avoir jamais aime, Rin fait alors le choix de combattre aux cotes des exorcistes, quitte a liberer, en degainant l epee de son pere, la puissance demoniaque qui sommeille en lui !', 'Telecharger');
INSERT INTO manga VALUES('12', 'Rosario Vampire', '24', '106', '2004', 'Shonen', 'Termine', 'Ecole, Romance, Action', 'Tsukune vient de rater son examen d entree au lycee et ses parents ont decide de l envoyer dans le lycee prive Yokai. C est un lieu etrange ou les eleves sont des monstres. Tsukune fait la rencontre de Moka, une camarade de classe vampire. Moka est devenu en peu de temps l idole du lycee, elle se prend d affection pour Tsukune mais leur amitie ne plait pas a tout le monde, notamment au caid de l ecole Saizo.', 'Telecharger');
INSERT INTO manga VALUES('13', 'Naruto', '72', '700', '1999', 'Shonen', 'Termine', 'Action, Aventure', 'Naruto est un garcon un peu special. Solitaire au caractere fougueux, il n est pas des plus apprecies dans son village. Malgre cela, il garde au fond de lui une ambition: celle de devenir un maitre Hokage, la plus haute distinction dans l ordre des ninjas, et ainsi obtenir la reconnaissance de ses pairs mais cela ne sera pas de tout repos... Suivez l eternel farceur dans sa quete du secret de sa naissance et de la conquete des fruits de son ambition!', 'Lu');
INSERT INTO manga VALUES('14', 'Uragiri', '12', '56', '2005', 'Shonen Ai', 'En Cours', 'Romance,Fantastique, Aventure', 'Depuis quelques temps, Yuki Sakurai fait des reves etranges dans lesquels un homme mysterieux apparait et lui promet de ne jamais le trahir. Au reveil, un doux sentiment de nostalgie lui etreint encore le coeur. D autant que sa vie n est pas simple, abandonne des son plus jeune age, il a grandi dans un orphelinat et ne connait rien de sa vraie famille. Il essaye de s en sortir seul en trouvant un petit boulot pour quitter l orphelinat. C est a ce moment qu il se fait attaquer par des demons. De jeunes personnes le sauvent et lui affirment qu il a un don et qu il s est reincarne pour les aider dans leur lutte. En effet, le jeune homme possede un don qui pour lui est plutot une malediction : il peut ressentir les emotions des personnes qu il touche. Mais qu en est-il de cette histoire de reincarnation? Ses reves seraient-ils lies a tout ?a?', 'Telecharger');
INSERT INTO manga VALUES('15', 'Prophecy', '3', '21', '2012', 'Shonen', 'Termine', 'Social, Thriller et Drame', 'La section de lutte contre la cybercriminalite de Tokyo est sur les dents. Un individu coiffe d un masque en papier journal poste sur Internet des videos mena?antes ou il predit les pires crimes : incendies, agressions, viols... Le probleme ? Des le lendemain, ses propheties se realisent a la une des journaux televises.
Qui est-il, comment procede-t-il, quelles sont ses motivations ? C est le debut d une course contre la montre qui mene les inspecteurs jusqu au siege vide d un cybercafe de la banlieue de Tokyo. Mais tandis que l enquete pietine, contre toute attente, le soutien populaire grandit autour du mysterieux personnage. Marginaux, employes tyrannises par leur hierarchie, internautes qui hantent les forums de discussion : ils sont de plus en plus nombreux a se retrouver dans son combat...', 'Acheter');
INSERT INTO manga VALUES('16', 'High School of Dead', '7', '30', '2010', 'Shonen', 'Termine', 'Ecchi, Horreur', 'Le monde fut contamine le 13 avril 2010 par une maladie mortelle d origine inconnue, qui apparait le meme jour dans les principales villes, transformant les humains en zombies et entrainant le declin de la civilisation. Au Japon, plusieurs etudiants du lycee Fujimi, ainsi qu une infirmiere scolaire, se sont regroupes afin de survivre a cette apocalypse. L histoire suit Takashi Komuro, l un des rares etudiants a avoir survecu a la premiere attaque.', 'Telecharger');
INSERT INTO manga VALUES('17', 'Saint Seiya', '28', '200', '1990', 'Shonen', 'Termine', 'Action, Aventure, Fantastique', 'Dans la mythologie Grecque, de jeunes garcons protegeaient la deesse Athena. Appeles les Chevaliers Sacres d Athena, on dit que de leurs mains ils pourfendaient le ciel et de leurs pieds ils entrouvraient la terre. De nos jours, suivez les aventures de Seiya, Shun, Ikki, Hyoga et Shiryu, les cinq fameux adolescents japonais devenus chevaliers d Athena afin de proteger la Terre des menaces qui pesent sur elle...', 'Acheter');
INSERT INTO manga VALUES('18', 'Good Ending', '16', '156', '2009', 'Shonen', 'Termine', ' Romance, Tranche de vie', 'Seiji Utsumi est un lyceen reserve. Il est secretement amoureux de la capitaine du club de tennis du lycee, Sho Iketani. Mais de peur de se prendre un rateau, il se contente de la regarder de loin. Jusqu au jour ou Yuki, une camarade de classe, lui renvoie a la figure son attitude pathetique et sans consulter le jeune homme, decide de donner un coup de pouce au destin', 'Acheter');
INSERT INTO manga VALUES('19', 'Trinity Seven', '12', '54', '2010', 'Shonen', 'En Cours', 'Fantastique, Magie, Aventure', 'Kasuga Arata est un adolescent des plus normal, qui vit avec sa cousine et amie d enfance Hijiri. Un jour il remarque que le soleil et la lune sont devenus noirs et qu il est le seul a s en rendre compte. Il rencontre alors une etrange jeune fille, Lilith , qui lui explique que son monde a ete detruit. Il vit en fait dans un monde virtuel qu il a lui meme cree a l aide d un Grimoire que lui a laisse sa cousine avant d etre absorbee par le soleil noir. Lilith est une eleve de l Academie Magicus, qui a ete envoyee pour retrouver le Grimoire. Menace de mort par cette derniere, Kasuga n a d autre choix que de rejoindre l Academie afin d apprendre la magie et tenter de retrouver sa cousine.', 'Acheter');
INSERT INTO manga VALUES('20', 'Dance in the Vampire Bund', '14', '82', '2005', 'Seinen', 'Termine', 'Ecchi, Romance, Fantastique', 'Apres des millenaires de clandestinite, Mina Tepes, la dirigeante du peuple vampire decide de reveler au grand jour son existence. Usant de la fortune accumulee par son clan, elle comble la dette nationale du Japon en echange de la creation d une zone independante ou les vampires pourront vivre entre eux. Pourtant, ce changement n est pas au gout de tout le monde et rapidement des opposants apparaissent...des deux cotes !', 'Acheter');
INSERT INTO manga VALUES('21', 'Saint Seiya Lost Canvas', '25', '223', '2009', 'Shonen', 'Termine', 'Action, Aventure, Fantastique', 'Tenma et Alone sont deux amis orphelins vivants au XVIIIe siecle. Un jour, Tenma est remarque par Doko, le Chevalier d or de la Balance. Il decide de l emmener en Grece pour l entrainer a devenir Chevalier de Bronze, protecteur de la deesse Athena. Alone, lui, rencontre une mysterieuse jeune fille, Pandore, qui voit en lui l hote ideal qui permettrait la reincarnation d Hades, Dieu des enfers. La Grande Guerre Sainte est sur le point de commencer.', 'Telecharger');
INSERT INTO manga VALUES('22', 'Amagami Morishima arc', '1', '6.5', '2009', 'Seinen', 'Termine', 'Romance', 'Il y a deux ans, Junichi Tachibana avait rendez-vous avec une fille le soir de Noel. Mais, sans savoir pourquoi, celle-ci ne vint jamais, et son coeur en fut brise. Depuis, par peur de se faire rejeter de nouveau, il n a jamais eu le courage de proposer a une autre fille de sortir avec lui. Et a chaque fois que la date de Noel approche, il se sent deprime. Mais la vie regorge de surprises. Cette annee, il fera des rencontres qui le pousseront a changer d avis et a passer un Noel rempli de bonheur.
Amagami SS propose ainsi de suivre plusieurs histoires d amour paralleles impliquant Junichi, en commencant par celle avec Haruka Morishima, et avec a chaque fois la meme situation de depart.', 'Telecharger');
INSERT INTO manga VALUES('23', 'Amagami Nanasaki arc', '1', '4.5', '2009', 'Seinen', 'Termine', 'Romance', 'Il y a deux ans, Junichi Tachibana avait rendez-vous avec une fille le soir de Noel. Mais, sans savoir pourquoi, celle-ci ne vint jamais, et son coeur en fut brise. Depuis, par peur de se faire rejeter de nouveau, il n a jamais eu le courage de proposer a une autre fille de sortir avec lui. Et a chaque fois que la date de Noel approche, il se sent deprime. Mais la vie regorge de surprises. Cette annee, il fera des rencontres qui le pousseront a changer d avis et a passer un Noel rempli de bonheur.
Amagami SS propose ainsi de suivre plusieurs histoires d amour paralleles impliquant Junichi, en commencant par celle avec Haruka Morishima, et avec a chaque fois la meme situation de depart.', 'Telecharger');
INSERT INTO manga VALUES('24', 'Ane Doki', '3', '26.5', '2009', 'Shonen', 'Termine', 'Romance, Comedie,Tranche de Vie', 'Depuis que Kouta lui a offert une glace, la jolie Natsuki a promis de s occuper de lui durant l absence de son pere. N importe quel garcon serait ravi de la situation, mais pas Kouta, qui n aime pas etre couve de la sorte. Mais le jeune garcon va changer d avis, le jour ou elle l aide a sauver la plus jolie fille de son ecole de 3 loubards...', 'Telecharger');
INSERT INTO manga VALUES('25', 'Ayu Mayu', '5', '29', '2009', 'Shonen', 'Termine', 'Comedie, Tranche de vie', 'Tres jeunes, Yousuke et sa soeur devinrent orphelins. Sa soeur a ete adoptee dix ans avant le debut de l histoire, depuis ce jour, il n a pas arrete de la chercher. Un jour Yousuke trouva le couple ayant adopte sa soeur, mais il y a un probleme, ce couple a deux filles, Ayu et Mayu, les deux sont issues du meme orphelinat et ont quasiment le meme age. Ayu et Mayu avaient toutes les deux un grand frere avant d etre adoptees. Les choses vont encore se compliquer quand Yousuke apprendra que l orphelinat ou il avait vecu a brule il y a de ca un an, que tout les registres ont ete detruit durant l incendie, et que ceux du couple semblent avoir disparus. Yousuke doit trouver laquelle des filles est sa vraie soeur.', 'Telecharger');
INSERT INTO manga VALUES('26', 'Battle Club', '9', '10', '2004', 'Seinen', 'Termine', 'Ecchi, Sport', 'Mokichi est un loser, pure souffre douleur de ses camarades de classe, et ce depuis sa plus tendre enfance. Bien decide a en finir avec cette vie difficile, il change de lycee et se met en tete de jouer les durs des son arrivee sur place. Mais au lieu de cela, le matin meme de sa nouvelle vie, il se fait a nouveau racketter devant tout l etablissement par une bandes de voyous. Apparaet devant lui une fille nommee Tamako qui va litteralement eclater ces racailles !! Comprenant la detresse de Mokichi, Tamako le prend sous son aile et l invite a rejoindre dans le club de lutte du lycee. Commence alors pour Mokichi une longue initiation au combat !! Mais tout n est pas si simple, car dans ce club, tous les membres sont de superbes jeunes filles !', 'Telecharger');
INSERT INTO manga VALUES('27', 'Beatless Dystopia', '2', '12', '2012', 'Shonen', 'Termine', 'Action, Suspense', '2105 A.D Japon
L humanoide android hIE prends une part dans la vie des gens et gere les choses que les humains ne peuvent pas faire. Endou Arato, contrairement a ses amis Kenko et Ryou qui detestent les hIE, ressens de la sympathie pour les hIE qui sont censes etre de simples objets. Une nuit, Arato se fait soudainement attaquer par la chute de mysterieuses fleurs de cerisier qui HIE qui rendent fous les hIE. Arato sera sauve par Lacia.', 'Telecharger');
INSERT INTO manga VALUES('28', 'Change 123', '12', '60', '2005', 'Shonen', 'Termine', 'Ecchi, Ecole, Arts martiaux ', 'Kosukegawa est un jeune otaku tres timide. Un jour, il tombe amoureux de Motoko Getto, une jeune fille de sa classe, apparemment tout ce qu il y a de plus normale... mais qui souffre de dedoublement de la personnalite ! En effet, lorsque celle-ci se trouve en mauvaise posture, elle cede sa place a HiFuMi, trois personnalites tres devastatrices : Hiromi, specialiste en lutte et en combat, Fujiko, maitresse en strategies et armes de toutes sortes, et enfin Mikiri, experte en techniques de soumissions (etranglements, cles de bras) et en combat rapproche. Comment vont evoluer les relations entre Motoko et Kosukegawa ?', 'Telecharger');
INSERT INTO manga VALUES('29', 'Claymore', '27', '155', '2001', 'Shonen', 'Termine', 'Action, Heroic-Fantasy', 'Les humains sont terrorises par des etres demoniaques capables de se fondre parmi eux. Leur seule chance de survie reside dans les mains des Claymores, des femmes hybrides mi-humaines mi-demons qui possedent des pouvoirs gigantesques, depassant meme ceux des demons. Habitant d un petit village, Raki rencontre l une d entre elles, envoyee en mission pour trouver et exterminer le demon qui decime les siens. Subjugue par la beaute de la jeune fille, il va decouvrir les terribles secrets qui se cache derriere l organisation Claymore et le destin tragique qui attend chacun de ses membres...', 'Telecharger');
INSERT INTO manga VALUES('30', 'Kenichi', '61', '583', '2002', 'Shonen', 'Termine', 'Sport, Action, Arts martiaux ', 'Kenichi SHIRAHAMA, grand amateur de livres et de jardinage, est victime de brimades dans son lycee, jusqu au jour ou Miu Furinji, une nouvelle eleve de sa classe, arrive dans son lycee. Apres une bagarre dans la rue ou elle le defend, il prend conscience de sa faiblesse et demande a Miu de lui apprendre a se battre. Elle l amene alors a un vieux dojo en apparence desaffecte, Ryozampaku. Il en rencontre alors les originaux mais impitoyables maitres, qui lui dispensent le plus dur des entrainements. Kenichi ne va pas tarder a decouvrir que Miu n est autre que la petite fille du plus grand d entre eux, et revele un certain talent pour les arts martiaux.Cela l abasourdit, d autant plus que la violence et les armes blanches le terrorisent, mais en meme temps, l attire de plus en plus vers Miu...', 'Telecharger');
INSERT INTO manga VALUES('31', 'KimiKiss Various Heroines', '1', '45', '2007', 'Seinen', 'Termine', 'Tranche de vie, Ecchi', 'Kouichi est un adolescent qui reve d etre populaire aupres des filles. Par le biais d une retrouvailles hasardeuse avec son amie d enfance, qui est depuis devenue une superbe jeune fille, il decouvrira les methodes qui vont le rendre digne de l attention qu il souhaite. Chaque volume aura pour sujet chacune des differentes filles qui pourrait devenir sa petite amie', 'Telecharger');
INSERT INTO manga VALUES('32', 'Kiryuuin Kaya', '3', '16', '2011', 'Ecchi', 'Termine', 'Surnaturel, Romance, Harem', 'C est un travail tranquille, se faire sucer le sang par Kaya Kiryuuin. Ou peut-etre pas ?', 'Telecharger');
INSERT INTO manga VALUES('33', 'Kisei Kanojo Sana', '1', '11', '2013', 'Ecchi', 'Termine', 'Harem, Surnaturel, Romance', 'Karato vit une vie comme les autres, il a ses amis et va a l ecole... Bref rien d anormal. Un matin, sa cousine Sakura au temperament un peu foufou lui offre un reveil... electrique ! Sa maison est envahie d elements chimiques, appartenant a son pere, un scientifique. Et ca s etale jusqu a la cuisine, dans laquelle Sakura lui gave son petit-dejeuner. Le soir venu, Karato souffre de douleurs intenses au ventre au point de croire qu il va mourir, et c est alors que son ventre se deforme et laisse sortir... Une fille nue ! Et pas une simple fille... Apparemment ce petit-dejeuner n etait pas si sain que ca...', 'Telecharger');
INSERT INTO manga VALUES('34', 'Negative Happy Chainsaw Edge', '1', '8', '2007', 'Shonen', 'Termine', 'Drame, Romance', 'Yamamoto, qui vient de perdre un ami dans un accident, lutte pour faire face aux autres problemes qui l assaillent : une session d examens a venir et un premier pas vers le crime. Quand a Eri Yukizaki, combattante mysterieuse, elle lutte sans cesse contre un homme invincible arme d une tronconneuse. Un jour, ces deux personnages maudits par le destin se rencontrent....', 'Telecharger');
INSERT INTO manga VALUES('35', 'Onihime VS', '4', '26', '2008', 'Seinen', 'Termine', 'Fantastique, Ecchi, Romance', 'Faible, brime par ses camarades de classe et victime de problemes cardiaques necessitant des soins onereux, Setsuna souffre par-dessus tout de n etre qu un gouffre financier pour sa soeur.
Alors qu il s apprete a faire le grand saut pour abreger cette vie miserable, un homme mysterieux lui propose un pacte : troquer sa vie contre 10 millions de yens. Sceptique, le jeune homme finit par accepter. Apparaissent alors Kanna et Rana, deux plantureuses et volcaniques demones. Dans un an, l une d entre elles aura le privilege de devorer le coeur de Setsuna. Qui aura les faveurs du jeune homme ? Et pourquoi semble-t-il desormais attirer les creatures demoniaques ?', 'Telecharger');
INSERT INTO manga VALUES('36', 'Sakura no uta', '1', '6', '2005', 'Seinen', 'Termine', 'Drame, Romance, Tranche de Vie', 'Kusanagi Naoya a perdu sa mere a un jeune age. Comme son pere etait un peintre qui a voyage a travers le monde, la seule personne qui pourrait aider Naoya a faire face a cette perte est son ami, Misakura Rin. Malheureusement, elle est partie alors qu ils etaient en ecole primaire...', 'Telecharger');
INSERT INTO manga VALUES('37', 'Soukyuu no Lapis Lazuli', '1', '11', '2013', 'Seinen', 'Termine', 'Harem, Surnaturel, Romance', 'Il y a une legende qui dit que celui qui reussira a rassembler les 99 Witchcraft que la grande sorciere Lily Valentine a laisses derriere elle apres sa mort se verra accorder un souhait... Alors que tout allait bien pour lui, Toya se fait soudainement attaquer par une enorme armure. Il est sauve in extremis par une fille qu il n avait pas vu depuis son enfance. Les evenements ont fait qu il vit desormais chez elle et sa soeur, qui sont en fait ses cousines. Il finit rapidement par entendre parler des Witchcraft, et alors que personne ne s y attendait, Toya et son groupe sont embarques dans une longue aventure pleine d excitation !', 'Telecharger');
INSERT INTO manga VALUES('38', 'The Breaker', '10', '72', '2007', 'Seinen', 'Termine', 'Action, Arts Martiaux', 'Un nouveau professeur, Chunwoo, arrive dans l ecole. Dragueur incorrigible a l attitude egoiste, le mauvais traitement que subit l un de ses eleves va pourtant le mener a lui devoiler une parfaite maitrise des arts martiaux. Shinwoo, le jeune eleve maltraite, fera tout ce qu il peut pour devenir son disciple, au grand dam de ce dernier. Une organisation d artistes martiaux seront prets a tout pour defier Chunwoo et de nombreux combats se preparent...', 'Telecharger');
INSERT INTO manga VALUES('39', 'To Love ru', '18', '162', '2006', 'Ecchi', 'Termine', 'Comedie, Romance, Harem', 'Alors que Rito avait enfin trouve le courage de declarer sa flamme a  Haruna, la plus jolie fille du lycee, Lala une extraterrestre en fuite qu il a sauve la veille se meprend sur ses paroles et decide de l epouser ! Et comme une bonne nouvelle n arrive jamais seule, Rito d?couvre que Lala princesse de son etat est courtisee par toute la galaxie. Il peut donc s attendre a ce que de nombreux pretendants viennent tenter d eliminer le geneur qu il est devenu !', 'Telecharger');
INSERT INTO manga VALUES('40', 'Unbalance x Unbalance', '10', '82', '2005', 'Seinen', 'Termine', 'Romance, Tranche de Vie', 'Jin Ho est un lyceen. Un jour il ramasse un porte-monnaie dans une librairie et il le rend a son proprietaire, Hye Young mais apres en avoir pique 7 euros. Hye Young le decouvre immediatement et lui demande de les rendre. Quelques jours plus tard, une rumeur court a l ecole selon laquelle le nouveau professeur principal qui va venir dans la classe de Jin Ho est un canon... Et a la surprise de Jin Ho, c est Hye Young qui arrive. C est ainsi que commence une relation qui s annonce houleuse.', 'Telecharger');
INSERT INTO manga VALUES('41', 'xxxHolic', '19', '160', '2003', 'Seinen', 'Termine', 'Magie,Drame,Tranche de vie', 'Lyceen, Kimihiro Watanuki est pousse malgre lui par une force etrange qui le fait entrer dans la maison d une medium, Yuko Ichihara, qui attendait cette visite ineluctable. Face a ses declarations, Kimihiro reste perplexe, et afin de parer a son scepticisme, la medium lui revele des details concernant son passe, notamment un lourd secret lie aux forces occultes. Pour se debarrasser des visions qui l assaillent, Kimihiro accepte un petit boulot d homme de menage chez cette medium plutot difficile a vivre...', 'Telecharger');
INSERT INTO manga VALUES('42', 'Zettai Joousei', '2', '10', '2010', 'Shonen', 'Termine', 'Romance, Tranche de Vie', 'Zettai Joousei raconte l histoire d un lyceen nomme Satou Yuuma qui souffre de mysogenie suite a une experience traumatisante au college. Sa grande soeur, Miharu, l a pousse a integrer l ecole dans laquelle elle officie en tant que nonne, le lycee Saint Meighan. Le petit detail interessant, c est que le ratio filles/gar?ons est 9:1 ! Par la suite, il va etre nomme secretaire de la Reine de l ecole...', 'Telecharger');
INSERT INTO manga VALUES('43', 'Negima', '38', '355', '2003', 'Shonen', 'Termine', 'Fantastique, Comedie, Romance', 'Negi Springfield est un jeune apprenti magicien de 10 ans qui vient tout juste de decrocher son diplome. Pour achever sa formation, une epreuve un peu curieuse lui est imposee : il doit quitter l Ecosse pour effectuer un stage de trois mois en tant que professeur d anglais dans une classe de filles au Japon ! Decouvrir un enseignant de quatre ans leur cadet etonne bien sur les 31 eleves de la classe 2-A du college Mahora, mais la plupart d entre elles finissent par s attacher a Negi, qu elles chouchoutent des qu elles en ont l occasion...', 'Telecharger');
INSERT INTO manga VALUES('44', 'Frogman', '6', '58', '2009', 'Ecchi', 'Termine', 'Romance, Ecchi', 'Michiru est un lyceen banal. Il aime regarder Haruka, une de ses camarades de classe, lorsqu elle nage. Cette derniere est l unique membre du club de natation du lycee. Pendant qu elle et son entraineuse recherchent des nouveaux membres, elle le voit et l invite a se joindre a elle, pensant qu il la regardait car il aimerait nager. Il n arrive pas a refuser l offre bien que ne sachant pas nager, et voit son univers changer a mesure qu Haruka lui donne des cours.', 'Telecharger');
INSERT INTO manga VALUES('45', 'Koibana Onsen', '9', '64', '2005', 'Ecchi', 'Termine', 'Erotique, Ecchi, Romance', 'Le Koibana Onsen est un onsen dirigee par 3 jolies soeurs. Akiyama, un jeune homme qui vient de se faire larguer, va rendre service aux jeunes femmes et rester travailler a l onsen.
De fil en aiguille, l histoire nous en apprend un peu plus sur l histoire des soeurs et sur l evolution des relations entre Akiyama et ces 3 soeurs pleines de charmes.', 'Telecharger/lu Anglais');
INSERT INTO manga VALUES('46', 'Kono Oneesan wa Fiction desu !', '8', '48', '2010', 'Seinen', 'Termine', 'Comedie,Romance', 'Tard une nuit ou Jun est dehors sur son velo, il rencontre par hasard une fille ivre, a moitie nue etendue sur le cote de la route. Elle est tres affectueuse, mais Jun l a ramene avec lui a sa maison pour dormir par courtoisie. Il s avere qu elle est Kawase Narumi, la nouvelle assistante de sa mere auteur. Malheureusement, elle n a aucune idee ce qu elle fait dans son nouveau travail, donc Jun doit la former. Il doit aussi gerer le faite qu elle a la mauvaise habitude de s enivre, surtout nu et caline. La vie de Jun ne sera jamais la meme!', 'Telecharger/lu Anglais');
INSERT INTO manga VALUES('47', 'Nana to Kaoru', '18', '156', '2009', 'Ecchi', 'Termine', 'Romance, Drame, Social', 'Kaoru, 18 ans, est un fetichiste de SM. Il reve secretement d une relation SM avec son amie d enfance et voisine Nana. Un jour, la mere de Kaoru transmet a Nana un sac que celle-ci doit cacher pour le forcer a etudier. Cependant, Nana decouvre chez elle le contenu du sac: les accessoires SM de Kaoru... Elle finit par essayer une combinaison en cuir presente dans le sac, mais elle la verrouille accidentellement et n a pas la clef !', 'Telecharger/lu Anglais');
INSERT INTO manga VALUES('48', 'Seishun Pop', '7', '47', '2009', 'Ecchi', 'Termine', 'Romance, Drame', 'Chaque jour Sakuta Gotou aime zoner en ecoutant son groupe prefere The incest, car elle lui fait sentir a l aise. Toutefois, ce groupe est tres discret et n a pas encore eu une performance en direct. Maintenant, quand la chance vient a Gotou de voir son idole Ive, la chanteuse du groupe, sur scene, il decouvre qu elle est l etudiante transferee dans la classe d a cote ... et de faire encore mieux, elle arrete le concert et l attrape en disant: J\'ai envie de vous voir. Qu est-ce qu il va faire maintenant? ', 'Telecharger/lu Anglais');
INSERT INTO manga VALUES('49', 'The Breaker New Waves', '21', '200', '2010', 'Seinen', 'Termine', 'Action, Arts Martiaux', ' Suite de The breaker.', 'Telecharger');
INSERT INTO manga VALUES('50', 'To Love Ru Darkness', '18', '77', '2012', 'Ecchi', 'Termine', 'Comedie, Romance, Harem', 'Spin-off de la serie To Love.
Suite eux revelation de Lala, Momo, sa petite soeur decide de prendre en main, la vie amoureuse de Rito, afin de faire de lui le digne heritier du trone de Deviluke! De son cote, Ombre doree s habitue peu a peu a la vie sur Terre, sans savoir que dans l ombre se profile une menace indicible risquant de changer sa vie et celle de ses amis a jamais...', 'Telecharger');
INSERT INTO manga VALUES('51', 'Umi no misaki', '13', '127', '2007', 'Seinen', 'Termine', 'Romance, Harem', 'Nagi Goto est un jeune adolescent qui realise un jour son reve : aller sur l ile d Okitsushima afin de se rendre dans un lieu bien particulier du nom de Umi no Misaki. Cet endroit, paysage de reve, est tres peu connu des habitants eux-memes mais il croise par chance une jeune fille qui l y emmene volontiers. Cette rencontre, a priori anodine, va sceller sa vie sur l ile mais aussi son destin.', 'Telecharger/lu Anglais');
INSERT INTO manga VALUES('52', 'UQ Holder', '14', '136', '2013', 'Shonen', 'En Cours', 'Fantastique, Comedie, Romance', 'Tota Konoe a un reve qui lui tient a coeur : rejoindre la capitale, perchee sur un pilier geant, et devenir celebre ! Mais s il veut quitter sa campagne, il va devoir remplir la condition imposee par le chef du village : battre Yukihime, une magicienne accomplie qui est egalement sa tutrice. Jour apres jour, Tota defie Yukihime dans l espoir de remporter enfin la victoire... Mais l arrivee d un chasseur de primes qui en veut a leur vie va sonner la fin de leur quotidien paisible !', 'Telecharger');
INSERT INTO manga VALUES('53', 'Welcome To el Palacio', '6', '44', '2007', 'Ecchi', 'En Pause', 'Romance, Sport, Comedie', 'Un jeune homme se retrouve amnesique apres avoir ete sauve de justesse d un accident de la route par un inconnu. Il est recueilli par son sauveur qui dirige une salle de lutte f?minine. En attendant qu il retrouve la m?moire, ce dernier l emploie comme domestique et lui fait arbitrer des combats...', 'Telecharger/lu Anglais');
INSERT INTO manga VALUES('54', 'Fortune Arterial', '7', '43', '2010', 'Seinen', 'Termine', 'Romance, Surnaturel', 'Kohei Hasekura est un etudiant qui est transfere dans une prestigieuse ecole publique. L academie Shuchikan se trouve sur l ile Tamatsu (au large du Japon) et le seul moyen d y aller, c est en bateau. Mais cette prestigieuse ecole cache un lourd secret. Certain de ses eleves sont des vampires! Et c est ainsi que Kohei va etre entraine dans tout cela.', 'Lu Anglais');
INSERT INTO manga VALUES('55', 'Natsu no Zenjistu', '5', '35.2', '2008', 'Seinen', 'Termine', 'Drame, Romance, Tranche de Vie', 'Tetsuo Aoki est un jeune etudiant peintre au temperament plutot sombre et melancolique. Akira Aizawa est quant a elle une elegante jeune femme d une trentaine deannee qui travaille dans une galerie d art. Tous les deux se rencontrent a la venue de l ete. Natsu no Zenjitsu suit le developpement de leur relation a travers ses joies et ses epreuves.', 'Telecharger');
INSERT INTO manga VALUES('56', 'Shinigami-sama to 4-nin no Kanojo', '1', '19', '2013', 'Seinen', 'Termine', 'Comedie, Harem, Surnaturel', 'Minaguchi Kaoru n a rien de special. Il n est pas bon en sport ou ? l ecole, n est pas dans un club, et il n est pas populaire. Il n a pas d amis et n est meme pas interesse par l une des filles qu il conna?t. Contrairement aux reveries de harem de ses pairs, il reve de trouver son veritable amour. Malheureusement , un shinigami vient de le tuer , tout simplement parce qu il est une sorte de dechet. Quand il halete son intention d embrasser la vie avec ses respirations finales, elle le reprend ! Tant qu il fait suite a ses intentions, il ne sera pas tue. Pour convaincre le shinigami que ses plans sont authentiques, il lui declare qu il va se confesser a la jeune fille qu il aime, le lendemain . Certain d etre en echec, il envoie des lettres d amour a quatre filles differentes . A sa grande surprise , elles sont toutes d accord pour etre sa petite amie . Maintenant , ce type affectueux a fini dans une sorte d histoire de harem, de quatres filles !', 'Telecharger');
INSERT INTO manga VALUES('57', 'Shinmai Mao no Keiyakusha', '1', '18', '2012', 'Shonen', 'Abandonnee', 'Ecchi, Fantastique, Romance', '\"He, tu disais vouloir une soeur, non ?\" C est la question que lui pose son pere a Tojo Basara, un lyceen de premiere annee. Il lui annonce egalement qu il va se remarier. Basara qui n avait jamais vecu avec des filles se retrouve soudainement entoure par deux nouvelles demi-soeurs, Mio et Maria. C est une vie paisible qui l attend, reveille le matin par la magnifique Mio et entretenu par la petite Maria... Enfin, c est ce qu il aurait aime croire. Il semblerait que les deux soeurs ne soient pas de simples humaines, bien loin de la ! L une etant la nouvelle reine des demons et l autre succube. Mais Basara revele egalement son vrai visage, il fait partie du clan des heros, qui est l ennemi naturel des demons. Tres vite, un ennemi attaque le groupe, c est alors que debute l histoire d une petite famille qui ne vit pas si paisiblement finalement...', 'Lu');
INSERT INTO manga VALUES('58', 'Monster Musume', '12', '51', '2012', 'Ecchi', 'En Cours', 'Monstre, Ecchi, Romance', 'Trois ans plus tot, le monde a appris l existence d autres especes humanoides sur Terre et celles-ci ont ete autorisees a s integrer dans la societe humaine par l entremise d echanges culturels. Kurusu Kimihito devient l hote d un Lamia (femme-serpent) a la suite d une erreur administrative, avec la tache de prendre soin d elle. Malheureusement, la jeune humanoide tombe eperdument amoureuse de lui et tente de le seduire par tous les moyens. Il y a cependant un hic : la loi interdit formellement les relations charnelles inter-especes, forcant Kurusu a repousser sans cesse ses avances', 'Lu Anglais');
INSERT INTO manga VALUES('59', 'Cross Manager', '5', '42', '2011', 'Shonen', 'Termine', 'Romance, Sport', 'A cause d une blessure au genou faites au foot, Sakurai ne peut plus pratiquer de sport. Recherchant un nouveau club sans sports ni competitions, il fait la connaissance de Toyoguchi Misora, une fille de son lycee accro au lacrosse. Remarquant qu elle est maladroite et tres mauvaise a ce sport, Sakurai l aide en lui donnant des conseils pour se donner bonne conscience. Eblouie par sa faculte d apprentissage, Toyoguchi tient absolument a faire de ce prodige le manager de son club de lacrosse. Quelque peu embete, Sakurai se voit dans l obligation de refuser. En plus de sa blessure physique, le choc psychologique est quant ? lui bien plus important et lui fait barriere pour rentrer a nouveau dans un club sportif. Mais ce n est pas sans compter sur la diabolique Misora qui le fera chanter afin de le faire rejoindre de force le poste de manager.', 'Lu');
INSERT INTO manga VALUES('60', 'Domestic no Kanojo', '10', '92', '2014', 'Shonen', 'En Cours', 'Drama, Ecchi, Harem, Romance', 'Ce soir, Natsuo perd sa virginite. Sa partenaire? Elle s appelle Rui et vient juste de le rencontrer aujourd hui. C est elle qui a lancee cette situation, en disant qu elle voulait simplement savoir ce qu il y a avait a apprendre sur le sexe. Elle ne veut pas commencer de relation de couple, et se fiche de Natsuo. Apres l acte, Natsuo ressens des remords pour avoir perdu sa virginite avec une fille qu il n aimait pas specialement. Il se sent surtout coupable d avoir trahi l enseignante dont il est eperdument amoureux, Hina. Un triangle amoureux excentrique se deploie, tandis que Natsuo, Rui et Hina, se retrouvent tous les trois a faire partie de la meme famille !', 'Lu Anglais');
INSERT INTO manga VALUES('61', 'Pastel', '30', '142', '2002', 'Ecchi', 'Abandonnee', 'Comedie,Romance,Tranche de Vie', 'Pastel raconte l histoire de Mugi Tadano, jeune adolescent dont le pere, photographe, le laisse souvent seul. Mugi rencontre un jour une jeune fille, Yuu Tsukiyaki. Il apprend en rentrant chez lui qu elle et sa petite soeur, Tsukasa, vont habiter avec lui car devenues orphelines. De la, Mugi, amoureux de Yuu, tentera de proteger leur bien-etre et de les rendre heureuses, tout en cherchant une solution pour se rapprocher d elle.', 'Lu Anglais');
INSERT INTO manga VALUES('62', 'Totsugami', '8', '42', '2009', 'Seinen', 'Abandonnee', 'Fantastique, Action, Suspense', 'Narukami Tasuku est a premiere vue un simple lyceen. Mais grace a des lunettes, il peut voir les esprits.', 'Lu Anglais');
INSERT INTO manga VALUES('63', 'Dance in Vampire the Bund (Spin off)', '1', '4', '2013', 'Seinen', 'Termine', 'Romance, Sunaturel, Romance', 'Spin-off de Dance In The Vampire Bund dans lequel on suit le combat de Sledge Hammer alias Seiji Hama.', 'Acheter');
INSERT INTO manga VALUES('64', 'Amatsuki', '8', '48', '2005', 'Seinen', 'Abandonnee', 'Fantastique, Aventure, Action', 'Tokidoki est un lyceen plutot nonchalant qui, pour combler ses lacunes en histoire, est gentillement envoye dans un musee. Mais ce musee est d un genre nouveau : il propose une veritable immersion virtuelle dans le Japon de l ere Edoau moyen de dispositif de lunettes revolutionnaires. Facetie du programme ou simple bug, le jeune homme se retrouve nez a nez avec un etre etrange chevauchant un animal monstrueux tout droit sorti du bestiaire folklorique japonais. Tout tourne a l horreur lorsque Tokidoki, blesse a l oeil gauche par la bete feroce, se retrouve prisonnier du Japon du XIXeme siecle alors que ses lunettes gisent sur le sol, brisees...', 'Acheter');
INSERT INTO manga VALUES('66', 'Kiss x Sis', '16', '108', '2004', 'Seinen', 'Abandonnee', 'Erotique, Comedie', 'Le pere de Keita vient de se remarier, aussi le jeune homme va desormais partager son quotidien avec ses deux nouvelles demi-soeurs, deux magnifiques jumelles qui vont vite tomber sous son charme, provoquant par consequent bien des histoires.', 'lu Anglais');
INSERT INTO manga VALUES('67', 'Baroque K/Night', '1', '11', '2013', 'Seinen', 'Termine', 'Ecchi, Fantaisie, Romance', 'Le lyceen solitaire Moribe Kyoya pensait qu il etait heureux d avoir la belle et mysterieuse lyceenne Baroque nouvellement transferee qui est venue lui parler. Ce qu il a ensuite su, car il recu une lettre d amour d amour lui disant de venir sur le toit, c est que la confession n etait pas exactement celle a ce qu il s attendait ...', 'Lu');
INSERT INTO manga VALUES('68', 'Papa no lukoto wo kikinasai', '3', '12', '2012', 'Shonen', 'Termine', 'Tranche de vie, Comedie', 'En etant accepte a l universite, une nouvelle vie a commencee pour Segawa Yuuta, se faire un nouvel ami, rencontrer quelqu un qu il aime, il passait la vie du college normallement. Cependant, tout changea lorsque l avion que sa soeur et son mari avait pris a disparu. Dans une piece six tatami (une chambre ou il ne tient que 6tatamis) qu il avait pris pour vivre seul, une ecoliere de premier cycle (tsundere), Sora, une ecoliere elementaire (petit d?mon), Miu, et Kindergardener, Hina, ont soudainement decide de vivre ensemble avec lui. Yuuta est devenu papa de 3 filles qui sont au milieu de la puberte! Le coeur battant avec ce nouveau style de vie avec des filles Yuuta voit sa vie chamboulee et en outre, impliquant des ennuis amour avec la sempai qu il aime.', 'Lu');
INSERT INTO manga VALUES('69', 'Love Hina', '14', '118', '1998', 'Shonen', 'Termine', 'Etudiants Romance', 'Keitar Urashima est un jeune homme de 20 ans qui essaie tant bien que mal d integrer la prestigieuse Tadai, afin de tenir la promesse qu il a faite e une fille quinze ans plus tot. Il caresse l idee de la revoir la-bas ; il a echoue deux fois au concours d entree, il ne se souvient plus du prenom de la jeune fille et sait encore moins a quoi elle ressemble.', 'Lu');
INSERT INTO manga VALUES('70', 'Hot Milk', '2', '10', '2000', 'Seinen', 'Termine', 'Comedie', 'Nous savons tous a quel point les gardes du corps n ont pas de travail au Japon (il suffit de lire City Hunter) ils sont donc pret a accepter n importe quel job, meme le plus dangereux pour avoir quelques yen, et si en plus il s agit de proteger une jeune et jolie lycenne, meme plus besoin de discuter le prix.
Et c est ainsi que Saruno, grand gaillard, va devoir s occuper de la petite fille d un Yakusa, Milk, si jamais il lui arrivait quelques chose, il peut dire adieu a son assurance vie.
Ce qu il ne se doute pas, c est que Milk a le don inne du sacrifice de soi au profit des autres, elle a monte un petit convenience store et aide tout ceux qui sont dans le besoin, cela inclu bien evidemment des combats contre gang, dealer, voleur et autre championne de Judo.', 'Lu');
INSERT INTO manga VALUES('71', 'Dracu Riot', '1', '12.5', '2012', 'Seinen', 'Termine', 'Romance Harem Surnaturel', 'Aqua Eden - Une ile artificielle flottante ou le jeu, la prostitution et le vol est autorise par le gouvernement. Mais il y a une chose qui se cache dans les rues de l ile, les vampires. Mutsura Yuto travaille avec l un d eux, et avec quelques autres membres de leur groupe, ils se battent pour faire respecter la morale sur l ile.', 'Lu Anglais');
INSERT INTO manga VALUES('72', 'Kanojo wa Kannou Shousetsuka', '5', '43', '2010', 'Seinen', 'Abandonnee', 'Comedie Romance Ecchi', 'Shiina Keisuke travaille pour une maison d edition qui s occupe de publier des nouvelles erotiques. Grand fan de Kuroki Chihiro, et adepte des saignements de nez torrentiels, notre jeune travailleur se voit un jour attribue par son chef, la mission de s occuper de son auteur preferee. Bien qu aux anges, le pauvre est loin de se douter de ce qui l attend', 'Lu Anglais');
INSERT INTO manga VALUES('73', 'One Piece', '75', '744', '1997', 'Shonen', 'Abandonnee', 'Action Pirate', 'Gol D. Roger etait connu comme le roi des pirates, l etre le plus fort et le plus tristement celebre pour avoir navigue Grand Line. La capture et la mort de Roger par le gouvernement mondial a apporte un changement dans le monde entier. Ses derniers mots avant sa mort ont revele l emplacement du plus grand tresor du monde, One Piece. Il etait cette revelation qui a provoque le Grand Age of Pirates, les hommes qui r?vaient de trouver One Piece (qui promet une quantite illimitee de richesses et de la gloire), et tres probablement le plus convoite de titres pour la personne qui l a trouve, le titre de le roi des pirates.', 'Telecharger');
INSERT INTO manga VALUES('74', 'Akame ga Kill', '15', '78', '2010', 'Shonen', 'Termine', 'Horreur Romance Tragedie', 'Tatsumi est un combattant qui debarque dans la capitale en esperant y realiser ses reves. Malheureusement il se fait depouiller de son argent par une jeune femme dans une taverne. Sans le sous et a la rue il fait la connaissance d une jeune noble qui lui propose de le loger pour la nuit. Ce qu il ne sait pas encore c est que sa protectrice va etre attaquee par un groupe d assassins...', 'Acheter');
INSERT INTO manga VALUES('75', 'Naruto Gaiden', '1', '10', '2015', 'Shonen', 'Termine', 'Action Aventure', 'Suite de Naruto Shippuden', 'Lu');
INSERT INTO manga VALUES('76', 'Lilim Kiss', '2', '24', '2010', 'Shonen', 'Termine', 'Sunaturel Romance', 'Takaya est un eternel incompris, car sous ses apparences de delinquant cool faisant craquer toutes les filles de son lycee se cache en fait un grand timide romantique. Et quand il delivre par accident Lilim, adorable demone de son etat, il ne sait pas encore qu il va se retrouver avec une vraie-fausse petite amie tres encombrante sur les bras. En effet, Lilim a besoin d aspirer la force des etres humains pour survivre, et le fait en les embrassant. Apres avoir aspire la force de la moitie male de la classe de Takaya, Lilim decide d aller habiter chez ce dernier, clamant que sa force est celle qui a le meilleur gout. Diverses peripeties comiques s ensuivent.', 'Lu');
INSERT INTO manga VALUES('77', 'Immortal Regis', '6', '44', '2009', 'Shonen', 'Termine', 'Ecchi Romance Fantastique', 'Lorsqu un jeune lyceen trouve la mort a cause d une sorciere malefique, il ne pensait pas que ce ne serait en realite que le debut de ses aventures. En effet, a present mort - vivant, il devra rapidement quitter notre monde au profit de Chaos, un univers parrallele ou regne la magie.', 'Lu');
INSERT INTO manga VALUES('78', 'Tende Freeze', '4', '36', '2008', 'Shonen', 'Termine', 'Comedie Surnaturel', 'Koyuki a le pouvoir de voir le futur, mais elle ne peut voir que les evenements malheureux qui arrivent aux gens.Jusqu au jour ou elle rencontre Umehachi, un lyceen, pour la premiere fois, elle peut voir le cote benefique qu elle peut tirer de ces situations...', 'Lu');
INSERT INTO manga VALUES('79', 'Spas Pa', '6', '31', '2002', 'Shonen', 'Termine', 'Romance Comedie', 'Prenons deux amis d enfance. D un cote nous avons un jeune homme qui voit les mauvais esprits et qui a fortement besoin d aide. De l autre nous avons une jeune fille dont la croissance a ete stoppe pour survivre (son esprit lui a evolue) et qui est specialise dans la chasse aux mauvais esprits. Voila un couple bien assorti... enfin sauf si notre heros n a pas le choix...', 'Lu');
INSERT INTO manga VALUES('80', 'Adrenalin', '4', '16', '2004', 'Shonen', 'Termine', 'Action Aventure', 'Lorsque Sunwoo Heeyong debarque a Seoul, il se trouve vite confronte a des problemes d argent. Mais voila qu il decouvre une annonce pour un logement a prix brade. Il est accueilli dans la somptueuse demeure par un groupe de jeunes femmes, toutes aussi seduisantes les unes que les autres. Le naif campagnard ignore qu elles s interessent surtout a son sang... Quel sort lui reservent-elles ?', 'Lu');
INSERT INTO manga VALUES('81', 'Princess Lucia', '4', '35', '2009', 'Ecchi', 'Termine', 'Surnaturel Comedie Romance', 'Koizumi Yuta est un garcon de 14 ans qui a un peu d un probleme. La princesse du monde magique, Lucia, a de procreer avec lui. Cet enfant aurait la capacite d engloutir le monde entier pendant 7 jours entiers. Mikamoto El Kasukabe et Rie sont les deux anges assignes a assurer que cela ne se produise pas. Kasukabe Rie se trouve etre la fille qu il aime. Juste comment est-ce qu il va survivre a cette epreuve?', 'Lu');
INSERT INTO manga VALUES('82', 'Tadashikunai Renai no Susume', '1', '7', '2013', 'Seinen', 'Termine', 'Adulte Mature Romance', 'Ichihara Tatsujou, une vierge de 21 ans, commence a dater Asahina Riko, une belle femme qui est inexplicablement interesse a lui. Apres les deux commencent dating, cependant, elle revele qu elle est seulement interesse par vierges que; des que les deux ont des rapports sexuels, elle le dumping. Refusant de renoncer a sa premiere petite amie, Tatsujou rend sa mission de convaincre Riko qu il y a plus a l amour d une courte aventure, se terminant apres le sexe. Dans le meme temps, Riko conclut qu elle seduira Tatsujou par tous les moyens necessaires, puis immediatement rompre avec lui.', 'Telecharger');
INSERT INTO manga VALUES('83', 'Shurabara Lovers', '1', '11', '2012', 'Seinen', 'Termine', 'Comedie Harem Romance', 'Yagimoto Kazuhiro est un lyceen connu pour la mise en couple, mais en realite, il veut juste avoir une petite amie lui-meme. Un jour, une des filles lui demande d etre son petit ami ... mais son pas ce qu il pense qu elle est.', 'Lu');
INSERT INTO manga VALUES('84', 'Kanokon', '9', '47', '2007', 'Seinen', 'Termine', 'Ecchi Harem Surnaturel', 'Kota Oyamada est un lyceen de premiere annee tout a fait normal. Tout change quand Chizuru Minamoto tombe amoureuse de lui. Elle est dans la meme ecole que lui mais pas dans la meme classe, car elle est plus agee que lui et naturellement perverse. Mais Chizuru n est pas ordinaire. Il est vrai qu elle est jolie et a une enorme poitrine, mais cette magnifique lyceenne n est pas humaine. C est un esprit-renard femelle.', 'Lu Anglais');
INSERT INTO manga VALUES('85', 'Sekirei', '18', '187', '2005', 'Ecchi', 'Termine', 'Ecchi Harem Surnaturel', 'Minato Sahashi est extremement intelligent, mais en raison de son incapacite a faire face sous pression a echoue a deux reprises l examen d entree au college. En consequence, il a ete marque un idiot et un perdant par beaucoup. Un jour, apres avoir parle a sa mere encore une fois decu, il entre en contact avec une jeune fille nommee Musubi qui etait sous attaque. La fille court, mais l emmene avec elle et decouvre bientot que Minato, tandis inconnu pour lui, est un Ashikabi, l un des mysterieux ensemble des maitres qui ont le trait genetique qui peuvent devenir des partenaires avec quelques-uns des 108 filles mignonnes, les femmes plantureuses, et Bishonen appele Sekirei. La raison pour laquelle le partenariat permet a la Sekirei a utiliser toute leur puissance pour gagner dans le concours organise par la societe MBI mysterieuse.', 'Lu Anglais');
INSERT INTO manga VALUES('86', 'Unbalance x3', '1', '58.2', '2015', 'Seinen', 'En Cours', 'Webcomic, Mature, Romance', 'Taehyun Choi et sa soeur Hakyung Choi vivent une vie tout ce qu il y a de plus normal a une exception pres: tout les oppose. Ainsi, en plus d etre belle et intelligente, Hakyung a une bonne situation alors que frere, Taehyun, est un cancre fini. Tout va basculer lorsqu il apprendra par hasard qu Hakyung n est pas sa soeur biologique. Au moment ou il voulut clarifier la situation avec elle, cette derniere perd la memoire dans un accident de la route. Comment les sentiments enfouis vont-ils emerger dans cette relation devenue trois fois plus compliquee dorenavant ?', 'Lu Anglais');
INSERT INTO manga VALUES('87', 'Shingetsutan Tsukihime', '8', '74', '2004', 'Seinen', 'Termine', 'Romance Surnaturel Horreur', 'Shiki Tohno est un garcon qui a miraculeusement survecu a un grave accident quand il etait petit. Depuis, il vit separe de son foyer. De plus, il a acquis un etrange don : il voit des lignes sur les objets et les hommes. Il s agit des lignes de la mort, qui permettent en les suivant de detruire l objet ou l etre vivant. Heureusement, Shiki s est vu offrir des lunettes qui empechent la vision de ces lignes de la mort. L histoire commence lorsque Shiki est convoque au foyer familial apres le deces de son pere.', 'Lu Anglais');
INSERT INTO manga VALUES('88', 'Kana', '4', '20', '1999', 'Shonen', 'Termine', 'Fantastique', 'Yuuji Abe rencontre une mysterieuse jeune fille a la station de metro. Cette rencontre fortuite avec Kana et Rou, son compagnon loup ;Yuuji empetre dans un complot ourdi par les 7 chefs , un groupe de demi-demons qui veulent apporter un type d utopie ou les humains et les demons peuvent vivre ensemble pacifiquement', 'Lu');
INSERT INTO manga VALUES('89', 'Spice and Wolf', '13', '80', '2007', 'Seinen', 'En Cours', 'Fantasy Aventure Romance', 'L histoire debute dans le village de Pasroe, au moment du festival de la moisson. Contrairement a la plupart des habitants du pays ou se deroule l histoire, les habitants de Pasroe sont paiens et croient en une divinite-loup : Holo. La legende raconte qu un pacte entre les hommes et les loups a ete conclu afin d assurer de bonnes recoltes de ble. Mais les villageois ne prennent plus la legende au serieux : c est grace a des methodes plus modernes que les recoltes sont devenues plus abondantes. Lawrence est un marchand ambulant, il vend par exemple de la fourrure et fait des echanges. Alors qu il s apprete a quitter le village, Lawrence decouvre a l arriere de sa carriole une jeune femme possedant des oreilles et une queue de loup, qui se presente comme la divinite des lieux. Elle demande a Lawrence de l emmener avec lui puisque les habitants ne semblent plus avoir besoin d elle.', 'Acheter');
INSERT INTO manga VALUES('90', 'Bloodline in the Dark', '1', '14.5', '2012', 'Ecchi', 'Termine', 'Romance Surnaturel Harem', 'Apres un accident, notre protagoniste Amagami Kouichi est implique avec Itanami-san une beaute bien connue de son ecole et secretement un vampire.', 'Lu Anglais');
INSERT INTO manga VALUES('91', 'Sword Art Online Aincrad', '2', '40', '2009', 'Light Novel', 'Termine', 'Jeux Romance Aventure', 'Il s agit du jeu du premier arc, Aincrad. Le monde prend la forme d un chateau flottant geant appele Aincrad, comportant 100 paliers. Chaque etage dispose d un cadre de style medieval et un donjon avec un boss, qui doit etre vaincu pour que les joueurs puissent acceder a l etage superieur. Comme la plupart des jeux de role, le jeu propose un systeme de niveau. Cependant, apres la periode de beta test, le createur du jeu a active un systeme pour pieger les joueurs a l interieur du jeu, empechant toute deconnexion. Si les joueurs meurent dans le jeu ou si leurs casques de realite virtuelle sont enleves, le cerveau du joueur recoit un flux de micro-ondes entrainant la mort.', 'Acheter');
INSERT INTO manga VALUES('92', 'Ookii Onnanko wa Daisuki desu ka', '3', '30', '2014', 'Ecchi', 'En Cours', 'Romance Harem Sports Adulte', 'Tachibana Souta est un peu un freeter multi- talentueux qui obtient par d un emploi a temps partiel pour la prochaine , son standout caracteristique etant qu il est un peu court. Un jour, il est encorde par sa soeur ainee dans servir l equipe de volleyball de leur college , dont elle est membre . Elle arrive aussi d etre au moins 6 et 1/2 pi . De hauteur, de meme que le reste des membres de l equipe qui prennent tout l interet Souta', 'Lu Anglais');
INSERT INTO manga VALUES('93', 'Re:Marina', '6', '49', '2013', 'Seinen', 'Termine', 'Romance Ecchii Comedie', 'Pere inutile et vagabond de Rinosuke est maintenant mort . Maintenant , a l age de 16 ans, il est completement seul et devra quitter l ecole pour survivre. Dans la nuit , son pere meurt , une femme nue avec de gros seins tombe du ciel et les terres au-dessus de lui. Elle se presente comme Sakamoto Marina , la future epouse du futur Rinosuke . Elle affirme qu elle a utilise une machine de temps a revenir au passe , et commencer une nouvelle vie avec la jeune Rinosuke . La nouvelle vie de Rinosuke avec son futur ( ? ) Femme commence .', 'Lu Anglais');
INSERT INTO manga VALUES('94', 'Nana to Kaoru: Black Label', '5', '45', '2010', 'Seinen', 'Termine', 'Romance Adulte Mature', 'L histoire d Arashi se deroule 8 mois apres la serie Nana to Kaoru. On retrouve nos deux heros Nana et Kaoru en plein ete durant leur annee de Terminale. L entourage et l endroit ou se passe cette suite sont differents de la trame principale ce qui ne laisse pr?sager aucun spoil. Mais ce qui est sur c est que ce sera toujours aussi chaud.', 'Telecharger');
INSERT INTO manga VALUES('96', 'Full Metal Alchemist', '27', '108', '2001', 'Shonen', 'Termine', 'Aventure Science-Fantasy', 'Dans le pays d Amestris, pays ou l Alchimie est elevee au rang de science universelle, deux freres, Edward et Alphonse Elric parcourent le monde a la recherche de la legendaire pierre philosophale dans le but de retrouver leurs corps perdus. Leur pere, Van Hohenheim, les a quittes il y a de cela des annees, et leur mere Trisha Elric meurt quelques annees plus tot d une maladie, laissant ses deux jeunes enfants derriere elle. Un an plus tard, les deux freres tentaient de la faire revenir grace a l alchimie, bravant la loi qui interdit formellement la transmutation humaine. Ils en payeront le prix fort. Edward, l aine, perdra sa jambe gauche, son petit frere perd son corps tout entier. Ed sacrifiera son bras droit en scellant l ame de son petit frere Alphonse dans une armure. Edward decide de s engager dans l armee a l age de 12 ans en tant qu Alchimiste d Etat, reussit l examen haut la main et obtient son nom d alchimiste, le Fullmetal Alchemist. Avec les avantages d alchimiste d etat et leurs recherches, les deux freres chercheront au peril de leur vie la pierre mythique qui leur rendra ce qu ils ont perdu, mais le secret de la Pierre Philosophale est bien garde.', 'Acheter');
INSERT INTO manga VALUES('97', 'Silver Spoon', '13', '113', '2011', 'Shonen', 'En Cours', 'Comedie Tranche de Vie Agriculture', 'Lorsqu il arrive au lycee agricole Ohezo, situe sur a Hokkaido au Nord du Japon, Yugo Hachiken croit que sa vie sera facile : avec tous ces fils de fermiers incapables d aligner deux equations, devenir premier de sa classe sera une partie de plaisir ! Mais c etait sans compter les cours d elevage, de sciences de la nutrition, de gestion agricole et les clubs de sport epuisants... Comment va-t-il faire pour survivre dans cette galere !?', 'Acheter');
INSERT INTO manga VALUES('98', 'Billionnaire Girl', '2', '17', '2009', 'Seinen', 'Termine', 'Romance Tranche de Vie Drame', 'Takato Kei est un etudiant universitaire ordinaire qui vit une vie ordinaire lorsqu il trouve un emploi a temps partiel etrange mais tout de meme attirant. Il est embauche pour etre le professeur particulier d une adolescente pour 10.000 yens de l heure. Cette fille en question n est pas lycenne, mais une trader qui a deja ramasse 170 milliards de Yens. Malgre son argent et son magnifique appartement, Kei ne peut s empecher de penser que Fujioka Yukari est une jeune fille solitaire. Elle semble obsedee par le marche bouriser et y depense d enormes actions. Kei parviendra-t-il a lui faire realiser que l argent ne fait pas le bonheur ', 'Lu Anglais');
INSERT INTO manga VALUES('99', 'Koisome Momji (One Shot)', '1', '1', '2012', 'Shonen', 'Termine', 'Comedie Romance Ecchi', 'Dans une certaine ville de campagne, une legende raconte que si vous trouvez une feuille d erable a huit pointes votre amour s epanouira.
Un film sur cette legende est en cours de production mettant en vedette Mizuhara Sana, une jeune lyceenne, l actrice en vogue du moment. N ayant aucune experience en amour, elle decide de sortir avec Aikawa Shouta, un lyceen qui a le beguin pour elle afin de s investir dans le role de son personnage.', 'Telecharger');
INSERT INTO manga VALUES('100', 'Love in the hell', '3', '18', '2011', 'Seinen', 'Termine', 'Comedie Romance Surnaturel', 'Rintaro Senkawa est un gars dans la vingtaine qui boit un peu trop une nuit et meurt. Mais c est juste le debut de l histoire de Rintaro qui se retrouve en enfer ou il fait la connaissance de son guide, une demone terriblement sexy, Koyori. Rintaro peut-il prendre cette situation suffisamment serieusement pour se repentir des peches de sa vie terrestre ou est-il destine a etre eternellement tente et torture par des demones en petites tenues aux massues herissees de pointes ?', 'Acheter');
INSERT INTO manga VALUES('101', 'IS2 Official Anthology', '1', '15', '2015', 'Ecchi', 'Termine', 'Mecha Romance Harem', '', 'Lu Anglais');
INSERT INTO manga VALUES('102', 'Sports Girl', '1', '27', '2015', 'Ecchi', 'Termine', 'Webtoons Sports Adulte', '', 'Lu Anglais');
INSERT INTO manga VALUES('103', 'Arslan Senki', '8', '47', '2015', 'Shonen', 'En Cours', 'Action Aventure Fantasy', 'A la suite d une trahison, le royaume de Parse est vaincu par son ennemi de toujours : Lusitania.
Heureusement, le prince de Parse, Arslan, 14 ans, est parvenu a s enfuir avec quelques amis fideles. Avec ses compagnons, il va alors tout mettre en oeuvre pour reconquerir son royaume mais aussi pour abolir un ordre social qu il deteste', 'Acheter/Lu Anglais');
INSERT INTO manga VALUES('104', 'Virgin na Kankei', '6', '47', '2001', 'Ecchi', 'Termine', 'Romance Adulte Harem', 'Kimijima est un travailleur indépendant qui cherche a devenir un membre actif de la societe . Apres une nuit de passion avec une belle femme va mal, il se trouve se precipiter pour faire une entrevue d emploi precoce. Cependant, l intervieweur se revele être la femme avec qui il a passe la nuit precedente', 'Lu Anglais');
INSERT INTO manga VALUES('105', 'Love Lucky', '7', '63', '2003', 'Seinen', 'Termine', 'Romance Adulte Mature', 'Fuuta est un salaryman moyenne prospectifs qui n a jamais eu de chance avec les femmes . Cependant , tout ce qui change quand il rencontre une fille etrange a travers une agence de rencontres . Elle est agreable , mais il a une etrange habitude de toujours porter des masques sur leurs dates . Un jour , Fuuta voit sa petite amie de port du masque etant attaque par ( ce qu il pense sont ) les voleurs . Fuuta la sauve d eux, et plein de bonheur et de gratitude , la jeune fille avoue et lui propose . Le soir, ils se marient , elle prend enfin son masque et revele son identite : Elle est la chanteuse super idole Kirari qui admire Fuuta Ainsi commence sa vie comme un couple marie .', 'Lu Anglais');
INSERT INTO manga VALUES('106', 'Kimiro Focus', '10', '40', '2009', 'Shonen', 'Termine', 'Ecchi Romance Harem', 'Ouji est un jeune garçon qui reve de devenir photographe. Cependant, son amie d enfance, Sumire, croit qu il ne pourra jamais réaliser son reve. Un jour, au club de photographie de son lycee, Ouji arrive a convaincre son amie de poser pour lui. Sumire s aperçoit alors qu il est totalement different lorsqu il se tient derriere l objectif.', 'Lu Anglais');
INSERT INTO manga VALUES('107', 'Orange', '5', '22', '2012', 'Shojo', 'Termine', 'Romance Poesie Sciences Fiction', 'Naho est une jeune lycéenne de seize ans vivant à Matsumoto, dans la préfecture de Nagano. Son quotidien est bouleversé par la réception d une lettre du futur. Elle aurait été écrite par Naho elle-même, dix ans plus tard. Cette Naho a désormais vingt-six ans et est rongée par les remords. Au travers de cette lettre, elle compte empêcher Naho de reproduire les mêmes erreurs. Ainsi, la lettre contient des éléments sur les événements des mois à venir et des instructions concernant principalement l arrivée d un nouvel élève dans la classe, Kakeru.', 'Acheter');
INSERT INTO manga VALUES('108', 'Ojousama no Untenshu', '2', '9.5', '2010', 'Shojo', 'Termine', 'Drame Romance Historique', 'Cette histoire ce passe à l ère Taisho, dans une école pour fille très réputée. Sayaka Yoshimura est d ailleurs la meilleure élève. Ce privilège est prouvé par le ruban rouge sombre qu elle a dans ses cheveux. Malgré ce rang, une rumeur court dans l école entre elle et son chauffeur qui se trouve toujours à ses côtés...', 'Lu / Lu Anglais');
INSERT INTO manga VALUES('109', 'Hajimete no Gal', '3', '32', '2015', 'Ecchi', 'En Cours', 'Comedie Romance Vie Scolaire', 'L été, la saison des amours est arrivée, mais trouver une petite amie pour Hashiba Junichi, un jeune lycéen, est plus dur qu il ne l espérait.
Pour l aider à trouver une petite amie, ses amis vont le forcer à se confesser à Yame Yukana, une gyaru. Toutefois, les choses ne se passent pas vraiment comme prévu car, aussi improbable que cela puisse paraître, Yukana accepte de sortir avec lui !', 'Lu');

